// Français Posé 📚
// Dictées et correction de phrases
const DICTEE_DATA=[
  // CP
  ['Le chat dort.','CP'],
  ['La balle est rouge.','CP'],
  ['Mon ami joue.','CP'],
  ['Le soleil brille.','CP'],
  ['Il fait beau.','CP'],
  // CE1
  ['Le chien court dans le jardin.','CE1'],
  ['Ma mère prépare le repas.','CE1'],
  ['Les enfants jouent au ballon.','CE1'],
  ['Le lapin mange des carottes.','CE1'],
  ['Elle lit un livre intéressant.','CE1'],
  ['Le petit chat boit du lait.','CE1'],
  ['Mon papa travaille tous les jours.','CE1'],
  ["Il fait beau aujourd'hui.",'CE1'],
  ['Je range mes affaires dans ma chambre.','CE1'],
  ['La maîtresse lit une belle histoire.','CE1'],
  // CE2
  ['Le petit chat blanc dort sur le canapé.','CE2'],
  ['Les grandes fleurs rouges poussent dans le jardin.','CE2'],
  ['Mon frère aime beaucoup le chocolat.','CE2'],
  ["Les enfants sont partis à l\'école.",'CE2'],
  ['Notre maison est à côté de la forêt.','CE2'],
  ['Le chat gris saute sur la chaise.','CE2'],
  ['Elle range ses affaires dans son cartable.','CE2'],
  ['Les élèves écrivent une belle histoire.','CE2'],
  ['Nous avons joué au foot avec nos amis.','CE2'],
  ['Le soir, ma grand-mère raconte des histoires.','CE2'],
  // CM1
  ['Le vieux château se dresse au sommet de la colline.','CM1'],
  ['La maîtresse corrige les cahiers de ses élèves.','CM1'],
  ['Pendant les vacances, nous allons à la montagne.','CM1'],
  ['Les élèves ont travaillé toute la journée avec sérieux.','CM1'],
  ['Le jardinier plante des fleurs sous le soleil du matin.','CM1'],
  ['Mon grand-père raconte de belles histoires le soir.','CM1'],
  ['Le renard roux traverse rapidement la forêt silencieuse.','CM1'],
  ['Chaque matin, elle prépare son cartable avec soin.','CM1'],
  // CM2
  ["Les beaux oiseaux blancs s\'envolaient au-dessus du lac.",'CM2'],
  ['La cuisinière préparait un délicieux gâteau au chocolat.','CM2'],
  ['Malgré le froid, les enfants jouaient dehors avec enthousiasme.','CM2'],
  ['La bibliothèque municipale possède des milliers de livres.','CM2'],
  ['Les explorateurs traversèrent la forêt pendant trois jours.','CM2'],
  ["Il avait soigneusement plié sa lettre avant de l\'envoyer.",'CM2'],
  // 6e
  ['Il était une fois une vieille sorcière qui vivait seule.','6e'],
  ['Les explorateurs parcouraient les forêts à la recherche de trésors.','6e'],
  ["Bien qu\'il fît froid, les enfants jouaient dehors avec enthousiasme.",'6e'],
  ['La rivière coulait doucement entre les rochers recouverts de mousse.','6e'],
  ['Depuis le sommet, on apercevait les lumières de la ville au loin.','6e'],
  ['Quoique fatigué, il poursuivit sa route sans se plaindre.','6e'],
  // 5e
  ["Lorsqu'elle arriva, tout le monde s'était déjà réuni autour de la table.",'5e'],
  ["Les scientifiques ont découvert une nouvelle espèce d'insecte en Amazonie.",'5e'],
  ["Le philosophe affirme que la connaissance est la source de la liberté.",'5e'],
  ["Il suffit parfois d'un seul mot pour changer le cours d\'une conversation.",'5e'],
  // 4e+
  ["Malgré ses efforts considérables, il n'avait pas réussi à convaincre ses adversaires.",'4e'],
  ["La beauté de ce paysage m'a profondément ému lors de mon premier voyage.",'4e'],
  ["Les hypothèses scientifiques doivent être vérifiées par l'expérience.",'4e'],
  ["Ce roman, dont l'intrigue se déroule au XVIIe siècle, est d'une grande complexité.",'3e'],
  // CE2
  ['Le soleil brille dans le ciel bleu.','CE2'],
  ['Mon chien court dans le jardin.','CE2'],
  ['Elle mange une pomme rouge.','CE2'],
  ['Les enfants jouent dans la cour.','CE2'],
  ['Le chat dort sur le canapé.','CE2'],
  ['Papa prépare le repas du soir.','CE2'],
  ['Nous allons à la piscine le samedi.','CE2'],
  ['La maîtresse écrit au tableau.','CE2'],
  ['Mon frère aime les bandes dessinées.','CE2'],
  ['Les oiseaux chantent au printemps.','CE2'],
  // CM1
  ['Le cheval galope dans la prairie.','CM1'],
  ["Elle a oublié son cahier à la maison.",'CM1'],
  ['Les élèves ont appris une belle leçon.','CM1'],
  ['Mon grand-père raconte des histoires passionnantes.','CM1'],
  ['Le vent souffle fort sur la montagne.','CM1'],
  ['Nous avons visité un musée extraordinaire.','CM1'],
  ['La neige recouvre les toits des maisons.','CM1'],
  ["Les fleurs s'épanouissent au soleil de mai.",'CM1'],
  // CM2
  ['Les hirondelles reviennent chaque printemps.','CM2'],
  ['Les alpinistes ont atteint le sommet hier.','CM2'],
  ['La bibliothèque municipale est ouverte tous les jours.','CM2'],
  ['Nous avons regardé les étoiles filantes hier soir.','CM2'],
  ['Cette histoire nous a tous profondément émus.','CM2'],
  ['Les chercheurs ont découvert une nouvelle espèce.','CM2'],
  // 6e
  ["Les navigateurs d'autrefois craignaient les tempêtes.",'6e'],
  ['Elle a résolu ce problème avec intelligence.','6e'],
  ['Le château médiéval domine la vallée depuis des siècles.','6e'],
  ['Ces tableaux ont été peints par des artistes célèbres.','6e'],
  ['Les volcans entrent parfois en éruption violente.','6e'],
  ["La forêt amazonienne abrite des milliers d'espèces.",'6e'],
  ['Les monuments historiques témoignent du passé.','6e'],
  // 5e
  ['Les scientifiques étudient les effets du changement climatique.','5e'],
  ["Cette découverte archéologique a surpris les historiens.",'5e'],
  ['Les révolutions scientifiques bouleversent nos certitudes.','5e'],
  ["Ces manuscrits enluminés datent du Moyen Âge.",'5e'],
  // 4e/3e
  ['La philosophie interroge les fondements de notre existence.','4e'],
  ["Cette œuvre littéraire a marqué profondément son époque.",'4e'],
  ['Les institutions démocratiques garantissent nos libertés fondamentales.','4e'],
  ["L'argumentation doit être rigoureuse et bien structurée.",'3e'],
  ["La maîtrise du langage est une condition de la liberté.",'3e'],
  // Lycée
  ["L'ambiguïté du texte suscite des interprétations divergentes.",'2de'],
  ["La vraisemblance est une condition du récit réaliste.",'2de'],
  ["Le personnage éponyme donne son nom à l'œuvre.",'1re'],
  ["L'implicite d\'un texte requiert une lecture attentive.",'1re'],
  ['La dissertation philosophique exige rigueur et nuance.','Tle'],
  ["L'irréductibilité de la conscience au cerveau est débattue.",'Tle'],
  // CP (suite)
  ['Le chien court.','CP'],
  ['Papa lit un livre.','CP'],
  ['Maman chante.','CP'],
  ['Je joue dehors.','CP'],
  ['Le chat dort.','CP'],
  // CE1 (suite)
  ['Les enfants courent dans le parc.','CE1'],
  ['Elle joue au ballon avec ses amis.','CE1'],
  ['Mon chien aboie le soir.','CE1'],
  ['Le maître explique la leçon.','CE1'],
  ['Nous regardons les étoiles la nuit.','CE1'],
  ['Le lapin mange des carottes.','CE1'],
  ['La grenouille saute dans la mare.','CE1'],
  ['Mon frère dessine de beaux avions.','CE1'],
  // CE2 (suite)
  ['Les petits poissons nagent dans le lac.','CE2'],
  ['Le facteur apporte le courrier chaque matin.','CE2'],
  ['Elle range soigneusement ses affaires.','CE2'],
  ['Mon grand-père raconte de belles histoires.','CE2'],
  ['Les nuages cachent le soleil.','CE2'],
  ['Nous cueillons des fleurs dans le pré.','CE2'],
  ['La cloche sonne la fin de la récréation.','CE2'],
  ['Les hirondelles volent très vite.','CE2'],
  // CM1 (suite)
  ['Les alpinistes préparent leur ascension avec soin.','CM1'],
  ['La rivière coule doucement entre les rochers.','CM1'],
  ['Mes parents organisent une grande fête dimanche.','CM1'],
  ['Elle a lu tous les livres de la bibliothèque.','CM1'],
  ['Le soleil se couche derrière les montagnes.','CM1'],
  ["Les fourmis transportent des provisions pour l'hiver.",'CM1'],
  ['Mon voisin cultive des légumes dans son jardin.','CM1'],
  ['Les enfants construisent un château de sable.','CM1'],
  ['La tempête a renversé plusieurs arbres.','CM1'],
  ['Elle prépare une surprise pour son anniversaire.','CM1'],
  // CM2 (suite)
  ['Les scientifiques observent les étoiles avec des télescopes.','CM2'],
  ['La manufacture produit des centaines de pièces par jour.','CM2'],
  ["Ces ruines témoignent d'une civilisation ancienne.",'CM2'],
  ['Il a parcouru des centaines de kilomètres à pied.','CM2'],
  ['Les équipes ont travaillé dur pour réussir ce défi.','CM2'],
  ['La géographie mondiale évolue avec le temps.','CM2'],
  ['Les élèves présentent leurs exposés devant la classe.','CM2'],
  ['Elle a composé une magnifique mélodie au piano.','CM2'],
  // 6e (suite)
  ["Les troubadours composaient des chansons d'amour.",'6e'],
  ["L'architecture gothique se caractérise par ses arcs en ogive.",'6e'],
  ["La Révolution française a bouleversé l'ordre social.",'6e'],
  ['Les légendes médiévales mettent en scène des chevaliers courageux.','6e'],
  ['Le détective examina chaque indice avec minutie.','6e'],
  ['Cette région produit un vin réputé dans le monde entier.','6e'],
  ['Les planètes orbitent autour du soleil à différentes vitesses.','6e'],
  ['Elle a interprété ce poème avec beaucoup de sensibilité.','6e'],
  // 5e (suite)
  ["L'industrialisation du XIX siècle a transformé les sociétés.",'5e'],
  ['Les philosophes grecs ont posé les bases de la pensée occidentale.','5e'],
  ["Ce roman explore les thèmes de la solitude et de l'exil.",'5e'],
  ['La chimie nous permet de comprendre la structure de la matière.','5e'],
  ["Ces fossiles datent de plusieurs millions d'années.",'5e'],
  ['La colonisation a eu des conséquences durables sur les civilisations.','5e'],
  // 4e
  ["L'auteur recourt à de nombreuses métaphores pour enrichir son texte.",'4e'],
  ['Le personnage principal traverse une profonde crise intérieure.','4e'],
  ['La tragédie classique respecte la règle des trois unités.','4e'],
  ["L'argumentation doit être appuyée par des exemples précis.",'4e'],
  ["Ces vers illustrent parfaitement la technique de l'enjambement.",'4e'],
  // 3e
  ['Le réalisme littéraire cherche à reproduire fidèlement la société.','3e'],
  ["L'inconscient freudien influence nos comportements quotidiens.",'3e'],
  ["Cette métonymie remplace le tout par l'une de ses parties.",'3e'],
  ["L'éloquence est l\'art de bien parler pour convaincre.",'3e'],
  // Lycée
  ["Le narrateur homodiégétique fait partie de l'histoire qu\'il raconte.",'2de'],
  ["Le naturalisme pousse le réalisme jusqu'à ses ultimes conséquences.",'2de'],
  ["L'hypotypose crée un tableau vivant par des détails saisissants.",'1re'],
  ["La prétérition consiste à dire qu'on ne dira pas ce qu\'on dit.",'1re'],
  ['Le cogito cartésien fonde la certitude sur le doute lui-même.','Tle'],
  ["L'impératif catégorique kantien régit l\'action morale universelle.",'Tle'],

  // ── Phrases supplémentaires ──
  ["Le chat dort sur le tapis.",'CP'],
  ["Papa lit un livre à la maison.",'CP'],
  ["Les oiseaux chantent dans les arbres.",'CP'],
  ["La petite fille mange une pomme.",'CP'],
  ["Le soleil brille dans le ciel bleu.",'CP'],
  ["Le chien court dans le jardin.",'CP'],
  ["Mon ami joue avec un ballon bleu.",'CP'],
  ["La lune brille la nuit.",'CP'],
  ["Les enfants jouent dans la cour.",'CE1'],
  ["Ma mère prépare un bon repas ce soir.",'CE1'],
  ["Le vent souffle fort dans les branches.",'CE1'],
  ["Les étoiles brillent dans le ciel noir.",'CE1'],
  ["La maîtresse écrit au tableau.",'CE1'],
  ["Le boulanger fait du pain frais chaque matin.",'CE1'],
  ["Les hirondelles annoncent le printemps.",'CE1'],
  ["Mon grand-père raconte de belles histoires.",'CE1'],
  ["Le petit lapin blanc mange des carottes.",'CE1'],
  ["Nous dessinons des fleurs dans nos cahiers.",'CE1'],
  ["Le fermier nourrit ses animaux chaque matin.",'CE2'],
  ["La neige recouvre les toits des maisons.",'CE2'],
  ["Mon frère répare sa bicyclette dans le garage.",'CE2'],
  ["Le jardinier taille les rosiers au printemps.",'CE2'],
  ["La tortue avance lentement sur le sentier.",'CE2'],
  ["Les hirondelles font leur nid sous les toits.",'CE2'],
  ["Nous avons planté des graines dans des petits pots.",'CE2'],
  ["Les élèves ont appris une belle poésie par coeur.",'CE2'],
  ["Le cheval galope dans la prairie verte.",'CE2'],
  ["Les papillons volent de fleur en fleur.",'CE2'],
  ["Les nuages gris annonçaient une tempête.",'CM1'],
  ["Le pêcheur lançait sa ligne au bord de la rivière.",'CM1'],
  ["Les châtaigniers perdent leurs feuilles en automne.",'CM1'],
  ["Nous avons observé les étoiles avec une longue-vue.",'CM1'],
  ["Le bibliothécaire range soigneusement les livres.",'CM1'],
  ["Les fourmis transportent des charges très lourdes.",'CM1'],
  ["Le menuisier fabrique des meubles en bois de chêne.",'CM1'],
  ["Les randonneurs ont aperçu un chevreuil dans la forêt.",'CM1'],
  ["Le potier façonne des vases avec de la terre glaise.",'CM1'],
  ["Les explorateurs ont découvert une île déserte.",'CM1'],
  ["Le capitaine ordonna à ses matelots de rentrer au port.",'CM2'],
  ["Les archéologues ont mis au jour des vestiges romains.",'CM2'],
  ["Ce vieux moulin à vent se dresse au sommet de la colline.",'CM2'],
  ["Les chevaliers du Moyen Âge portaient une armure pesante.",'CM2'],
  ["Les artisans fabriquaient des poteries avec de la terre.",'CM2'],
  ["Les paysages de montagne étaient couverts de neige immaculée.",'CM2'],
  ["La bibliothèque possède une collection de manuscrits anciens.",'CM2'],
  ["Le détective examina attentivement les indices laissés.",'CM2'],
  ["Les scientifiques étudient les effets du changement climatique.",'CM2'],
  ["Le navigateur observait attentivement les étoiles.",'CM2'],
  ["Les conquistadors espagnols soumirent les civilisations précolombiennes.",'6e'],
  ["Le naturaliste observait avec patience les animaux sauvages.",'6e'],
  ["Les troubadours parcouraient les châteaux pour réciter leurs poèmes.",'6e'],
  ["Les vignerons récoltent leur raisin en septembre.",'6e'],
  ["La lumière du soleil se décompose en arc-en-ciel.",'6e'],
  ["Les aristocrates jouissaient de nombreux privilèges injustes.",'6e'],
  ["Le cartographe dressait les cartes des territoires inexplorés.",'6e'],
  ["Les fossiles nous renseignent sur les espèces disparues.",'6e'],
  ["Le philosophe grec cherchait le sens de la vertu.",'6e'],
  ["Les cathédrales gothiques s'élancent vers le ciel.",'6e'],
  ["La Renaissance italienne vit naître des génies extraordinaires.",'5e'],
  ["Les philosophes des Lumières remettaient en question les dogmes.",'5e'],
  ["Les chevaliers templiers défendaient les routes vers Jérusalem.",'5e'],
  ["Les navigateurs utilisaient les étoiles pour se repérer en mer.",'5e'],
  ["La déforestation menace gravement la biodiversité tropicale.",'5e'],
  ["Les réformes économiques transformèrent la société médiévale.",'5e'],
  ["Ce poème baroque joue avec les contrastes entre ombre et lumière.",'5e'],
  ["Les ambassadeurs négociaient la paix entre les deux royaumes.",'5e'],
  ["Les révolutionnaires proclamèrent les droits de l'homme en 1789.",'4e'],
  ["Les personnages balzaciens incarnent les passions de leur époque.",'4e'],
  ["Les soldats endurèrent des conditions inhumaines dans les tranchées.",'4e'],
  ["Ces métaphores filées traversent l'ensemble du poème avec cohérence.",'4e'],
  ["Le naturaliste Darwin élabora sa théorie après un long voyage.",'4e'],
  ["L'industrialisation provoqua un exode rural massif.",'4e'],
  ["L'auteur use d'une ironie mordante pour critiquer la société.",'4e'],
  ["Les guerres napoléoniennes remodelèrent la carte de l'Europe.",'4e'],
  ["La rhétorique distingue le logos, l'ethos et le pathos.",'3e'],
  ["Le roman réaliste décrit la société avec exactitude.",'3e'],
  ["La métaphore crée un écart entre sens littéral et sens figuré.",'3e'],
  ["Les surréalistes exploraient l'univers du rêve et de l'inconscient.",'3e'],
  ["Le théâtre de l'absurde remet en question le sens de l'existence.",'3e'],
  ["L'hyperbole amplifie la réalité pour produire un effet saisissant.",'2de'],
  ["Le classicisme impose des règles strictes d'unité au théâtre.",'2de'],
  ["La tragédie racinienne met en scène des héros déchirés.",'2de'],
  ["Le symbolisme cherche à suggérer l'indicible par les mots.",'2de'],
  ["Les moralistes du dix-septième siècle peignaient les travers humains.",'2de'],
  ["La prétérition consiste à énoncer ce que l'on prétend taire.",'1re'],
  ["Les romantiques faisaient du moi souffrant la source de la poésie.",'1re'],
  ["Le roman polyphonique donne la parole à de multiples consciences.",'1re'],
  ["La focalisation interne plonge le lecteur dans la conscience d'un personnage.",'1re'],
  ["L'impératif catégorique exige d'agir selon une maxime universalisable.",'Tle'],
  ["Le marxisme analyse l'histoire comme la lutte des classes.",'Tle'],
  ["La déconstruction remet en question les oppositions binaires.",'Tle'],
  ["La phénoménologie étudie les structures de l'expérience consciente.",'Tle'],

  // ── Additions
  ['Le chat noir dort sur le tapis.','CP'],
  ['La petite fille lit un livre.','CE1'],
  ['Le soleil brille aujourd\\\'hui.','CE1'],
  ['Mange ta soupe avant de jouer.','CE1'],
  ['Les oiseaux chantent dans le jardin.','CE2'],
  ['Il pleut, prends ton parapluie.','CE2'],
  ['La maîtresse explique la leçon.','CE2'],
  ['Nous allons à la bibliothèque demain.','CE2'],
  ['Malgré la pluie, les enfants ont joué dans la cour.','CM1'],
  ['La solution proposée paraît simple mais demande du temps.','CM1'],
  ['Il faut vérifier les résultats avant de publier.','CM1'],
  ['La bibliothèque conserve des manuscrits rares et précieux.','CM1'],
  ['La recherche scientifique exige rigueur et patience.','CM2'],
  ['Le professeur corrige les copies avec attention.','CM2'],
  ['Les élèves préparent un exposé sur le climat.','CM2'],
  ['La ville organise une exposition d\\\'aquarelles.','CM2'],
  ['La solution durable exige une réflexion collective et patiente.','5e'],
  ['Il faut parfois réitérer l\\\'expérience pour confirmer le résultat.','4e'],
  ['Quiconque persévère finit par trouver son chemin.','5e'],
  ['Le prototype fonctionnel a été présenté au jury.','5e'],
  ['L\\\'analyse approfondie révèle des tendances intéressantes.','3e'],
  ['La méthodologie adoptée garantit la reproductibilité des résultats.','3e'],
  ['En dépit des difficultés, elle persévéra jusqu\\\'au bout.','4e'],
  ['Le rapport préliminaire sera soumis au comité la semaine prochaine.','4e'],
  ['La dissertation exige une argumentation structurée et nuancée.','2de'],
  ['L\\\'étude comparative met en lumière des divergences conceptuelles.','1re'],
  ['La problématique posée appelle une réflexion ontologique et épistémologique.','Tle'],
  ['L\\\'interprétation heuristique du texte ouvre des pistes de recherche.','Tle'],

  ['La méthodologie adoptée garantit la reproductibilité des résultats.','3e'],
  ['La corrélation observée nécessite une analyse plus approfondie.','4e'],
  ['La variable indépendante a été manipulée avec soin.','5e'],
  ['Les paramètres expérimentaux ont été consignés dans le protocole.','4e'],
];

// ── Phrases à corriger ──
// [phrase_erreur, mot_faux, correction, [distracteurs_morphologiques], explication, minLvl]
// RÈGLE : les 3 distracteurs sont des variantes morphologiques du mot correct.
const PHRASE_CORR=[

  // ════ ACCORD SUJET–VERBE ════
  ['Les enfants joue dans le jardin.','joue','jouent',
    ['joue','joues','jouons'],
    'Sujet pluriel "les enfants" → terminaison -ent.','CE2'],
  ['Le chien aboie et les chats fuit.','fuit','fuient',
    ['fuit','fuis','fuyons'],
    '"Les chats" est pluriel → fuient.','CE2'],
  ['Les oiseaux chante dans les arbres.','chante','chantent',
    ['chante','chantes','chantons'],
    'Sujet pluriel → -ent.','CE2'],
  ['Le chat et le chien mange ensemble.','mange','mangent',
    ['mange','manges','mangeons'],
    'Deux sujets coordonnés = pluriel → -ent.','CM1'],
  ['Vous doit travailler plus sérieusement.','doit','devez',
    ['doit','doivent','dois'],
    '"Vous" → "devoir" prend -ez.','CM1'],
  ['Ils court très vite sur la piste.','court','courent',
    ['court','courts','courez'],
    '"Ils" → terminaison -ent pour courir.','CE2'],
  ['Mon père et ma mère travaille beaucoup.','travaille','travaillent',
    ['travaille','travailles','travaillons'],
    'Deux sujets = pluriel → -ent.','CM1'],
  ["Ni lui ni elle ne vient aujourd\'hui.",'vient','viennent',
    ['vient','viens','venez'],
    '"Ni… ni…" avec deux sujets → pluriel.','5e'],
  ["C\'est moi qui a raison.",'a','ai',
    ['a','as','avons'],
    '"Qui" reprend "moi" (1re pers. sing.) → j\'ai.','5e'],
  ['Chacun de ces élèves doivent réussir.','doivent','doit',
    ['doivent','doivez','doit'],
    '"Chacun" est singulier → doit.','4e'],
  ['La plupart des élèves a réussi.','a','ont',
    ['a','as','avons'],
    '"La plupart de" suivi d\'un pluriel → ont.','4e'],

  // ════ ACCORD DE L\'ADJECTIF ════
  ['Elle a acheté des roses rouge.','rouge','rouges',
    ['rouge','rougit','rouges'],
    '"Roses" féminin pluriel → adjectif en -es.','CE2'],
  ['Les garçons semblaient très content.','content','contents',
    ['content','contente','contentes'],
    'Adjectif attribut masculin pluriel → -s.','CM1'],
  ['Le chat et la chienne sont belle.','belle','beaux',
    ['belle','belles','bel'],
    'Deux sujets dont un masculin → masculin pluriel.','CM2'],
  ['Les filles paraissaient très fatigué.','fatigué','fatiguées',
    ['fatiguée','fatigués','fatigué'],
    'Adjectif attribut féminin pluriel → -ées.','CM1'],
  ['Ce sont des histoires passionnant.','passionnant','passionnantes',
    ['passionnant','passionnants','passionnante'],
    '"Histoires" féminin pluriel → -antes.','CM2'],
  ['Il a les yeux grand ouvert.','grand','grands',
    ['grande','grandes','grand'],
    '"Yeux" masculin pluriel → -s.','CM2'],
  ['Elle semble très heureux.','heureux','heureuse',
    ['heureux','heureuses','heureusement'],
    'Sujet féminin singulier → heureuse.','CM1'],
  ['Des résultats inattendu ont surpris tout le monde.','inattendu','inattendus',
    ['inattendue','inattendues','inattendu'],
    '"Résultats" masculin pluriel → -s.','CM2'],
  ['Elle portait une robe vert foncé.','vert','vert',
    ['verts','vertes','verte'],
    '"Vert foncé" = adjectif de couleur composé : invariable.','3e'],
  ['Des fleurs bleu marine ornaient la table.','bleu','bleu',
    ['bleue','bleues','bleus'],
    'Les adjectifs de couleur composés (bleu marine) sont invariables.','3e'],

  // ════ PARTICIPE PASSÉ AVEC ÊTRE ════
  ['Les élèves sont arrivé en retard.','arrivé','arrivés',
    ['arrivé','arrivée','arrivées'],
    'Avec "être", accord masculin pluriel → -és.','CM2'],
  ['Nous sommes aller au cinéma hier.','aller','allés',
    ['aller','allé','allées'],
    'Avec "être", participe accordé avec le sujet.','5e'],
  ["Elle est tombé dans l\'escalier.",'tombé','tombée',
    ['tombé','tombés','tomber'],
    'Sujet féminin singulier → -ée.','CM2'],
  ['Mes sœurs sont parti en voyage.','parti','parties',
    ['partis','partie','partir'],
    'Sujet féminin pluriel → -ies.','CM2'],
  ['Il est rentré, elle aussi est rentré.','rentré','rentrée',
    ['rentrés','rentrer','rentrai'],
    'Sujet féminin → accord en -ée.','CM2'],
  ['Les filles se sont disputé dans la cour.','disputé','disputées',
    ['disputés','disputée','disputer'],
    'Verbe pronominal + sujet féminin pluriel → -ées.','5e'],
  ["Elle s\'est levé très tôt ce matin.",'levé','levée',
    ['levés','lever','levai'],
    'Sujet féminin avec verbe pronominal → -ée.','5e'],
  ['Nous nous sommes promené en forêt.','promené','promenés',
    ['promenée','promenées','promener'],
    '"Nous" masculin pluriel → -és.','5e'],
  ['Les portes se sont fermé brusquement.','fermé','fermées',
    ['fermés','fermer','fermai'],
    '"Portes" féminin pluriel → -ées.','5e'],

  // ════ PARTICIPE PASSÉ AVEC AVOIR ════
  ["Les lettres que j\'ai écrit sont belles.",'écrit','écrites',
    ['écrit','écrits','écrire'],
    '"Lettres" COD féminin pluriel avant → -es.','5e'],
  ["La chanson qu\'il a composé est belle.",'composé','composée',
    ['composé','composés','composer'],
    '"Chanson" COD féminin singulier avant → -ée.','5e'],
  ['Les films que nous avons regardé étaient bons.','regardé','regardés',
    ['regardé','regardée','regarder'],
    '"Films" COD masculin pluriel avant → -és.','5e'],
  ['Elle les a tous invité à sa fête.','invité','invités',
    ['invité','invitée','inviter'],
    '"Les" COD masculin pluriel avant → -és.','5e'],
  ['Quelle décision avez-vous pris ?','pris','prise',
    ['pris','prises','prendre'],
    '"Décision" COD féminin singulier avant → -e.','4e'],
  ["Les cadeaux qu\'elle nous a offert étaient magnifiques.",'offert','offerts',
    ['offerte','offertes','offrir'],
    '"Cadeaux" COD masculin pluriel avant → -s.','4e'],
  ['Les efforts que tu as fourni ont payé.','fourni','fournis',
    ['fournie','fournies','fournir'],
    '"Efforts" COD masculin pluriel avant → -s.','4e'],

  // ════ HOMOPHONES ════
  ['On a beaucoup de choses a faire.','a','à',
    ['a','as','ont'],
    '"À" préposition ≠ "a" verbe avoir.','CE2'],
  ['Il a mit son manteau avant de sortir.','mit','mis',
    ['mit','mît','mettre'],
    'Participe passé de "mettre" = "mis".','CM2'],
  ["Elle c'est trompée de chemin.",'c\'est','s\'est',
    ["c'est","c'était","s'était"],
    '"S\'est" = passé composé pronominal.','CM2'],
  ['Le chat dort sur sont coussin.','sont','son',
    ['sont','ont','mon'],
    '"Son" = déterminant possessif ≠ "sont" verbe être.','CE2'],
  ['Il ce couche tôt tous les soirs.','ce','se',
    ['ce','ses','ces'],
    '"Se" = pronom réfléchi (se coucher).','CM1'],
  ['Je ne sais pas si ont peut venir.','ont','on',
    ['ont','on','sont'],
    '"On" = pronom sujet ≠ "ont" verbe avoir.','CM1'],
  ['Il faut faire sont travail sérieusement.','sont','son',
    ['sont','ont','ton'],
    '"Son" = déterminant possessif (son travail).','CE2'],
  ['Tu peut venir demain si tu veux.','peut','peux',
    ['peut','peuvent','pouvons'],
    '"Tu" → "pouvoir" : tu peux (pas tu peut).','CM2'],

  // ════ ORTHOGRAPHE ════
  ['Il est toujours fatigé après le sport.','fatigé','fatigué',
    ['fatigé','fatiguais','fatiguer'],
    '"Fatigué" s\'écrit avec un u avant le é.','CE2'],
  ['La maitresse a expliqué la leçon.','maitresse','maîtresse',
    ['maitresse','maîtresses','maîtrèsse'],
    '"Maîtresse" prend un accent circonflexe sur le î.','CM2'],
  ['Il pleut, prenez vos paraluies.','paraluies','parapluies',
    ['paraluies','parapluie','para-pluies'],
    '"Parapluie" : p-a-r-a-p-l-u-i-e.','CM1'],
  ['Le soldat a fait preuve de bravure.','bravure','bravoure',
    ['bravure','braveur','braveure'],
    '"Bravoure" s\'écrit avec un o.','CM2'],
  ["L\'athlète s\'est bléssé au genou.",'bléssé','blessé',
    ['bléssé','blessée','blessés'],
    '"Blessé" : un seul accent, deux s, pas d\'accent sur le e.','CM2'],



  // ════ CE2/CM1 — erreurs de base ════
  ['Le chien a perdu ses os.','ses','ses',
    ['ses','son','leurs'],
    '"Son" est singulier, "ses" est pluriel. "Les os" → "ses os".','CE2'],
  ['Elle a mangé trop de gateau.','gateau','gâteau',
    ['gateau','gâteaux','gâteaus'],
    '"Gâteau" prend un accent circonflexe sur le a.','CE2'],
  ['Les enfants joue dans la cour.','joue','jouent',
    ['joue','jouent','jouez'],
    '"Les enfants" est 3e personne du pluriel → jouent.','CE2'],
  ['Il a beaucoup de ami.','ami','amis',
    ['ami','amies','amis'],
    'Après "de", le nom prend le pluriel si quantité > 1.','CE2'],
  ['Ma sœur est partie a Paris.','a','à',
    ['a','à','as'],
    '"À" préposition de lieu ≠ "a" verbe avoir.','CE2'],
  ['Mon frère range ses jouet.','jouet','jouets',
    ['jouet','jouets','jouer'],
    '"Ses jouets" : jouet au pluriel après "ses".','CE2'],
  ['Les filles sont heureuse.','heureuse','heureuses',
    ['heureuse','heureux','heureuses'],
    '"Les filles" féminin pluriel → heureuses.','CE2'],
  ['Il a prit son manteau.','prit','pris',
    ['prit','pris','prend'],
    'Participe passé de prendre = "pris".','CM1'],
  ['Nous avons bien travaillé ce matin.','travaillé','travaillé',
    ['travaillé','travailler','travaillés'],
    '"Avoir" + PP invariable ici : "avons travaillé".','CM1'],
  ['Elle ce brosse les dents chaque soir.','ce','se',
    ['ce','se','ces'],
    '"Se" = pronom réfléchi (se brosser).','CM1'],

  // ════ CM2/6e — accord, participe ════
  ['Mes parents sont revenus de voyage.','revenus','revenus',
    ['revenus','revenu','revenues'],
    '"Revenir" avec être : accord sujet masc. plur. → revenus.','CM2'],
  ['Elle a couru tout la journée.','tout','toute',
    ['tout','toute','tous'],
    '"Toute la journée" : toute féminin singulier.','CM2'],
  ['Ils ont dit que ont viendrait.','ont','on',
    ['ont','on','sont'],
    '"On viendrait" = pronom sujet indéfini.','CM2'],
  ['Le soldat a fais preuve de courage.','fais','fait',
    ['fais','fait','faits'],
    'Participe passé de "faire" = "fait".','CM2'],
  ['Les fleurs que tu as cueillie sont belles.','cueillie','cueillies',
    ['cueillie','cueillies','cueillit'],
    'COD "fleurs" féminin pluriel avant → cueillies.','6e'],
  ['Elle est tombée de sont vélo.','sont','son',
    ['sont','son','mon'],
    '"Son vélo" = déterminant possessif.','6e'],
  ['Ces élèves travaillent sérieusement, on les félicites.','félicites','félicite',
    ['félicite','félicites','félicitent'],
    '"On" sujet singulier → on les félicite.','6e'],
  ['Les résultats sont meilleurs que prévu.','meilleurs','meilleurs',
    ['meilleurs','meilleures','meilleur'],
    '"Résultats" masc. plur. → meilleurs.','6e'],
  ['Il a pas fais ses devoirs.','fais','fait',
    ['fais','fait','faits'],
    '"A fait" : participe de faire invariable.','6e'],
  ['Il faut que tu as fini avant ce soir.','as','aies',
    ['as','aies','avais'],
    '"Il faut que" exige le subjonctif : tu aies fini.','6e'],

  // ════ 5e — subjonctif, infinitif, gérondif ════
  ['En rentrant chez lui, la pluie tomba.','chez lui','il vit tomber la pluie',
    ['chez lui','il vit tomber la pluie','la pluie tombait'],
    'Le sujet du gérondif doit être le même que le sujet principal.','5e'],
  ["Il a besoin que tu viens l'aider.",'viens','viennes',
    ['viens','viennes','venais'],
    '"Avoir besoin que" + subjonctif.','5e'],
  ["Bien qu'il ait raison, il resta silencieux.",'ait','ait',
    ['ait','a','avait'],
    '"Bien que" + subjonctif : il ait raison.','5e'],
  ['Elle a fait nettoyer sa voiture.','nettoyer','nettoyer',
    ['nettoyer','nettoyé','nettoyée'],
    '"Faire + infinitif" : le PP de "faire" est invariable.','5e'],
  ["Je doute qu'il viendra demain.",'viendra','vienne',
    ['viendra','vienne','venait'],
    '"Douter que" + subjonctif.','5e'],
  ['Il parle en bégayant.','bégayant','bégayant',
    ['bégayant','bégayé','bégayer'],
    'Le gérondif se forme avec "en" + participe présent.','5e'],
  ['Il se rappelle de son enfance.','de son','son',
    ['de son','son','de ses'],
    '"Se rappeler" (sans de) : il se rappelle son enfance.','5e'],
  ['Malgré sa fatigue, il continua de travailler.','Malgré que','Bien que',
    ['Malgré que','Bien que','Quoique'],
    '"Malgré que" est critiqué ; préférer "bien que" + subjonctif.','5e'],

  // ════ 4e/3e — registres, styles ════
  ['Il est moins grand que son frère.','que','que',
    ['que','de',"qu'"],
    '"Plus/moins + adjectif + que" → comparatif.','4e'],
  ['Elle a obtenu les même résultats.','même','mêmes',
    ['même','mêmes','mème'],
    '"Les mêmes résultats" : même prend un s au pluriel.','4e'],
  ['Ils se sont tous regardé.','regardé','regardés',
    ['regardé','regardés','regardées'],
    'Verbe pronominal réciproque : "se regarder" → regardés.','4e'],
  ['On peux vraiment lui faire confiance.','peux','peut',
    ['peux','peut','pouvons'],
    '"On" sujet → on peut (3e personne du singulier).','4e'],
  ["Elle a beau essayer, elle n'y arrive pas.",'n\'y','y',
  ["n\'y",'y','ne'],
    '"Avoir beau" + infinitif, pas de négation supplémentaire.','4e'],
  ["Je n'ai pas pu venir faute de temps.",'faute de','faute de',
    ['faute de','manque de','à cause du manque de'],
    '"Faute de" (sans article) est correct.','3e'],
  ['Les résultats sont meilleurs de prévu.','de','que',
    ['de','que','qu\'il'],
    '"Meilleur que" → comparatif avec "que".','3e'],
  ['Il a résolu à ce problème.','à ce','ce',
    ['à ce','ce','de ce'],
    '"Résoudre" est transitif direct : il a résolu ce problème.','3e'],
  ['Elle parle de façon trop rapide.','rapide','rapide',
    ['rapide','rapidement','trop'],
    '"De façon rapide" ou "rapidement" sont tous deux corrects.','3e'],
  ["Nous nous sommes rendus compte de l'erreur.",'rendus','rendu',
    ['rendus','rendu','revenues'],
    '"Se rendre compte" : le PP "rendu" est invariable.','3e'],

  // ════ Lycée — stylistique, registre soutenu ════
  ['Il a pallié au problème rapidement.','pallié au','pallié',
    ['pallié au','pallié à','pallié'],
    '"Pallier" est transitif direct : il a pallié le problème.','2de'],
  ["Suite à l'incident, la réunion fut annulée.",'Suite à','À la suite de',
    ['Suite à','À la suite de','Suite de'],
    '"Suite à" est critiqué en contexte formel.','2de'],
  ['Cette solution est différente à la précédente.','différente à','différente de',
    ['différente à','différente de','différent de'],
    '"Différent de" (pas "à").','2de'],
  ['Il a agi pour ne faire que le strict nécessaire.','que le','que le',
    ['que le','que du','que de'],
    '"Ne... que" + groupe nominal : correct ici.','1re'],
  ['Selon moi, ce film est le meilleur de tous.','de tous','de tous',
    ['de tous','que tous','parmi tous'],
    '"Le meilleur de tous" est correct (superlatif absolu).','1re'],
  ['Il tient compte des remarques qui lui ont été soumises.','soumises','soumises',
    ['soumises','soumis','soumise'],
    'COD "remarques" féminin pluriel avant → soumises.','1re'],
  ['La décision incombe aux dirigeants de la prendre.','de la','de',
    ['de la','de','d\'en'],
    '"Incomber à qn de + inf." est correct.','Tle'],
  ['Nonobstant ses efforts, il échoua.','Nonobstant','Nonobstant',
    ['Néanmoins','Cependant','Malgré'],
    '"Nonobstant" (soutenu) = malgré : correct.','Tle'],
  // LYCEE avance
  ['La plupart des eleves etait absents.','etait','etaient',
    ['etait','etaient','sont'],
    'La plupart + nom pluriel = verbe au pluriel.','3e'],
  ['On entend les oiseaux chantes dans les arbres.','chantes','chanter',
    ['chantes','chanter','chantant'],
    'Apres un verbe de perception, on emploie infinitif.','4e'],
  ['Peu de candidats ont reussi ce concours.','ont reussi','ont reussi',
    ['ont reussi','a reussi','avait reussi'],
    'Peu de candidats = sujet pluriel, verbe au pluriel.','2de'],
  // ════ CONJUGAISON (temps, mode) ════
  ['Demain, nous partons en vacances hier.','hier','demain',
    ['hier','autrefois','jadis'],
    '"Demain" annonce le futur → contradiction avec "hier".','CE2'],
  ["Si j\'aurai le temps, je viendrai.",'aurai','avais',
    ['aurai','aurais','ai'],
    'Avec "si" hypothétique, on emploie l\'imparfait, pas le futur.','4e'],
  ["Bien qu\'il est fatigué, il continua.",'est','soit',
    ['est','était','sera'],
    '"Bien que" exige le subjonctif.','3e'],
  ['Il faudrait que tu viens demain.','viens','viennes',
    ['viens','venais','venez'],
    '"Il faut que" exige le subjonctif → tu viennes.','3e'],
  // ════ CE2 — erreurs fondamentales ════
  ['Les fleur du jardin sont belles.','fleur','fleurs',
    ['fleur','fleurs','fleures'],
    'Après "Les", le nom prend un s au pluriel.','CE2'],
  ['Le chien a perdu son os préférer.','préférer','préféré',
    ['préférer','préféré','préférés'],
    'Adjectif épithète du nom "os" → préféré (participe passé adjectif).','CE2'],
  ['Elle a mangé tout le gâteaux.','gâteaux','gâteau',
    ['gâteau','gâteaux','gâteaus'],
    '"Tout le" + singulier : "tout le gâteau".','CE2'],
  ['Il est rentré a la maison.','a','à',
    ['a','à','as'],
    '"À" préposition ≠ "a" verbe avoir.','CE2'],
  ['Les enfants ont jouer dans la cour.','jouer','joué',
    ['jouer','joué','jouez'],
    'Passé composé : "ont" + participe passé → joué.','CE2'],

  // ════ CM1 — accords, conjugaison ════
  ['Elle chante une belle chansonnes.','chansonnes','chanson',
    ['chanson','chansons','chansonnes'],
    '"Une belle chanson" : singulier, pas de s.','CM1'],
  ['Les chevaux courent rapidement.','courent','courent',
    ['courent','cours','court'],
    '"Les chevaux" 3e pers. pluriel → courent. Correct.','CM1'],
  ['Il a couru plus vite que moi.','couru','couru',
    ['couru','courait','courir'],
    '"Avoir + couru" : participe passé invariable avec avoir.','CM1'],
  ['Les oiseaux a chanté toute la nuit.','a','ont',
    ['a','ont','avons'],
    '"Les oiseaux" sujet pluriel → ont chanté.','CM1'],
  ['Elle a mis ses chaussure.','chaussure','chaussures',
    ['chaussure','chaussures','chaussurer'],
    '"Ses" déterminant pluriel → chaussures avec s.','CM1'],

  // ════ CM2 — participes, accords complexes ════
  ['Elles se sont disputés hier soir.','disputés','disputées',
    ['disputés','disputées','disputé'],
    'Verbe pronominal réciproque, sujet féminin pluriel → disputées.','CM2'],
  ['Il est tombée de son vélo.','tombée','tombé',
    ['tombée','tombé','tomber'],
    '"Il" sujet masculin + être → tombé (sans e).','CM2'],
  ['Les filles que tu as invitée sont venues.','invitée','invitées',
    ['invitée','invitées','inviter'],
    'COD "filles" féminin pluriel avant → invitées.','CM2'],
  ['Il nous a tout racontés.','racontés','raconté',
    ['racontés','raconté','raconter'],
    '"Tout" COD neutre → PP invariable : raconté.','CM2'],

  // ════ 6e — subjonctif, infinitif ════
  ['Il faut que tu fini tes devoirs.','fini','finisses',
    ['fini','finisses','finiras'],
    '"Il faut que" + subjonctif : tu finisses.','6e'],
  ['Bien que je suis fatigué, je travaille.','suis','sois',
    ['suis','sois','serai'],
    '"Bien que" + subjonctif : je sois.','6e'],
  ["Je doute qu'il peut venir.",'peut','puisse',
    ['peut','puisse','pourra'],
    '"Douter que" + subjonctif : il puisse.','6e'],
  ['Il faut que nous finissons à temps.','finissons','finissions',
    ['finissons','finissions','finirons'],
    'Subjonctif présent de "finir" : nous finissions (pas -ons).','6e'],
  ['Elle veut que tu viens demain.','viens','viennes',
    ['viens','viennes','viendras'],
    '"Vouloir que" + subjonctif : tu viennes.','6e'],

  // ════ 5e — gérondif, accord PP ════
  ["En lisent ce roman, j'ai pleuré.",'lisent','lisant',
    ['lisent','lisant','lus'],
    'Gérondif = "en" + participe présent : en lisant.','5e'],
  ["Les romans que j'ai lu sont magnifiques.",'lu','lus',
    ['lu','lus','lue'],
    'COD "romans" masculin pluriel avant → lus.','5e'],
  ['Elle a fait faire ses devoirs.','fait faire','fait faire',
    ['fait faire','fais faire','faites faire'],
    '"Faire" + infinitif : "fait" reste invariable.','5e'],
  ['Les résultats se sont avérés corrects.','avérés','avérés',
    ['avérés','avéré','avérées'],
    '"Se avérer" : accord avec sujet "résultats" masc. plur. → avérés.','5e'],

  // ════ 4e — registres, niveaux ════
  ["Elle s'est souvenue de lui immédiatement.",'souvenue','souvenue',
    ['souvenue','souvenu','souvenues'],
    '"Se souvenir" : accord avec le sujet féminin sing. → souvenue.','4e'],
  ['Les enfants se sont lavés les mains.','lavés','lavé',
    ['lavés','lavé','lavées'],
    'COD "les mains" après le verbe → PP invariable.','4e'],
  ["Il s'en est voulu d\'avoir menti.",'voulu','voulu',
    ['voulu','voulue','voulus'],'"S\'en vouloir" : PP invariable (en = pronom indéfini).','4e'],
  ["Elle a l'air fatiguée.",'fatiguée','fatiguée',
    ['fatiguée','fatigué','fatiguées'],'"Avoir l\'air" + adj. : accord avec le sujet → fatiguée.','4e'],
  ['Il parle en professionnel.','en professionnel','en professionnel',
    ['en professionnel','comme un','professionnellement'],
    '"En + nom sans article" est correct pour exprimer la manière.','4e'],

  // ════ 3e — style, syntaxe ════
  ['Après avoir manger, il se reposa.','manger','mangé',
    ['manger','mangé','mangeant'],
    '"Après avoir" + infinitif passé : après avoir mangé.','3e'],
  ['Il a du partir sans rien dire.','du','dû',
    ['du','dû','des'],'","Devoir" au passé composé → il a dû.','3e'],
  ['Nous nous sommes téléphoné hier soir.','téléphoné','téléphoné',
    ['téléphoné','téléphonés','téléphonée'],'"Se téléphoner" : PP invariable (pas d\'accord avec COD).','3e'],
  ['Les fleurs ont embaumer toute la pièce.','embaumer','embaumé',
    ['embaumer','embaumé','embaumet'],
    'Passé composé : "ont" + participe passé → embaumé.','3e'],

  // ════ Lycée ════
  ["Ce sont eux qui l'ont dit.",'l\'ont','l\'ont',
  ["l'ont",'l\'ont dit','ont'],'"Ce sont eux qui l\'ont dit" est correct.','2de'],
  ['Il est le seul à qui je fasse confiance.','fasse','fasse',
    ['fasse','fait','ferai'],
    '"Le seul à qui" + subjonctif est correct.','2de'],
  ['Force lui est de reconnaître ses torts.','lui est','lui est',
    ['lui est','est','lui sera'],
    '"Force est de" (locution impersonnelle) : correct.','1re'],
  ["C'est à vous à qui je pense.",'à vous à qui','à vous que',
    ['à vous à qui','à vous que','de vous que'],'"C\'est + pronom + que" (pas deux prépositions).','1re'],
  ['Nonobstant ces difficultés, il réussit.','Nonobstant','Nonobstant',
    ['Malgré','Quoique','Néanmoins'],
    '"Nonobstant" (préposition formelle) = malgré : correct.','Tle'],
];

// ── Genre des noms ── [mot, genre_correct, [faux], minLvl]
