// Français Posé 📚
// Verbes et conjugaisons irrégulières
// ══════════════════════════════════════════════════
// FRANÇAIS POSÉ — data.js  (version enrichie)
// Règle des distracteurs : toujours des variantes
// du même mot ou des leurres sémantiquement proches.
// Jamais un mot venu d'une autre entrée au hasard.
// ══════════════════════════════════════════════════

// ── Verbes ── [infinitif, groupe, auxiliaire, participe_passé, niveau_min]
const VERB_LIST=[
  // CP
  ['être',3,'et','été','CP'],['avoir',3,'av','eu','CP'],
  // CE1
  ['aimer',1,'av','aimé','CE1'],['parler',1,'av','parlé','CE1'],
  ['chanter',1,'av','chanté','CE1'],['danser',1,'av','dansé','CE1'],
  ['jouer',1,'av','joué','CE1'],['regarder',1,'av','regardé','CE1'],
  ['écouter',1,'av','écouté','CE1'],['travailler',1,'av','travaillé','CE1'],
  ['chercher',1,'av','cherché','CE1'],['trouver',1,'av','trouvé','CE1'],
  ['donner',1,'av','donné','CE1'],['penser',1,'av','pensé','CE1'],
  ['rester',1,'et','resté','CE1'],['arriver',1,'et','arrivé','CE1'],
  ['montrer',1,'av','montré','CE1'],['tourner',1,'av','tourné','CE1'],
  ['porter',1,'av','porté','CE1'],['manger',1,'av','mangé','CE1'],
  ['dessiner',1,'av','dessiné','CE1'],['entrer',1,'et','entré','CE1'],
  ['tomber',1,'et','tombé','CE1'],['monter',1,'et','monté','CE1'],
  ['marcher',1,'av','marché','CE1'],['sauter',1,'av','sauté','CE1'],
  ['crier',1,'av','crié','CE1'],['pleurer',1,'av','pleuré','CE1'],
  ['couper',1,'av','coupé','CE1'],['poser',1,'av','posé','CE1'],
  ['laver',1,'av','lavé','CE1'],['fermer',1,'av','fermé','CE1'],
  ['oublier',1,'av','oublié','CE1'],['décider',1,'av','décidé','CE1'],
  ['habiter',1,'av','habité','CE1'],['aider',1,'av','aidé','CE1'],
  ['acheter',1,'av','acheté','CE1'],['appeler',1,'av','appelé','CE1'],
  // CE2
  ['commencer',1,'av','commencé','CE2'],['bouger',1,'av','bougé','CE2'],
  ['nager',1,'av','nagé','CE2'],['rentrer',1,'et','rentré','CE2'],
  ['passer',1,'av','passé','CE2'],['lever',1,'av','levé','CE2'],
  ['ranger',1,'av','rangé','CE2'],['choisir',2,'av','choisi','CE2'],
  ['finir',2,'av','fini','CE2'],['grandir',2,'et','grandi','CE2'],
  ['préparer',1,'av','préparé','CE2'],['expliquer',1,'av','expliqué','CE2'],
  ['traverser',1,'av','traversé','CE2'],['rencontrer',1,'av','rencontré','CE2'],
  ['lancer',1,'av','lancé','CE2'],['avancer',1,'av','avancé','CE2'],
  ['reculer',1,'av','reculé','CE2'],['grimper',1,'av','grimpé','CE2'],
  ['glisser',1,'et','glissé','CE2'],['plonger',1,'av','plongé','CE2'],
  // CM1
  ['espérer',1,'av','espéré','CM1'],['répéter',1,'av','répété','CM1'],
  ['voyager',1,'av','voyagé','CM1'],['rougir',2,'av','rougi','CM1'],
  ['réfléchir',2,'av','réfléchi','CM1'],['réussir',2,'av','réussi','CM1'],
  ['obéir',2,'av','obéi','CM1'],['nourrir',2,'av','nourri','CM1'],
  ['punir',2,'av','puni','CM1'],['faire',3,'av','fait','CM1'],
  ['dire',3,'av','dit','CM1'],['prendre',3,'av','pris','CM1'],
  ['venir',3,'et','venu','CM1'],['voir',3,'av','vu','CM1'],
  ['savoir',3,'av','su','CM1'],['pouvoir',3,'av','pu','CM1'],
  ['vouloir',3,'av','voulu','CM1'],['devoir',3,'av','dû','CM1'],
  ['mettre',3,'av','mis','CM1'],['partir',3,'et','parti','CM1'],
  ['sortir',3,'et','sorti','CM1'],['aller',3,'et','allé','CM1'],
  ['rappeler',1,'av','rappelé','CM1'],['améliorer',1,'av','amélioré','CM1'],
  ['utiliser',1,'av','utilisé','CM1'],['terminer',1,'av','terminé','CM1'],
  ['observer',1,'av','observé','CM1'],['installer',1,'av','installé','CM1'],
  ['remplacer',1,'av','remplacé','CM1'],['accepter',1,'av','accepté','CM1'],
  // CM2
  ['agir',2,'av','agi','CM2'],['établir',2,'av','établi','CM2'],
  ['tenir',3,'av','tenu','CM2'],['recevoir',3,'av','reçu','CM2'],
  ['boire',3,'av','bu','CM2'],['croire',3,'av','cru','CM2'],
  ['écrire',3,'av','écrit','CM2'],['lire',3,'av','lu','CM2'],
  ['descendre',3,'et','descendu','CM2'],['résoudre',3,'av','résolu','CM2'],
  ['remplir',2,'av','rempli','CM2'],['subir',2,'av','subi','CM2'],
  ['fournir',2,'av','fourni','CM2'],['accomplir',2,'av','accompli','CM2'],
  // 6e
  ['connaître',3,'av','connu','6e'],['suivre',3,'av','suivi','6e'],
  ['vivre',3,'av','vécu','6e'],['courir',3,'av','couru','6e'],
  ['ouvrir',3,'av','ouvert','6e'],['offrir',3,'av','offert','6e'],
  ['sentir',3,'av','senti','6e'],['dormir',3,'av','dormi','6e'],
  ['servir',3,'av','servi','6e'],['rire',3,'av','ri','6e'],
  ['plaire',3,'av','plu','6e'],['cueillir',3,'av','cueilli','6e'],
  ['mentir',3,'av','menti','6e'],['battre',3,'av','battu','6e'],
  ['peindre',3,'av','peint','6e'],['joindre',3,'av','joint','6e'],
  // 5e
  ['conduire',3,'av','conduit','5e'],['construire',3,'av','construit','5e'],
  ['naître',3,'et','né','5e'],['mourir',3,'et','mort','5e'],
  ['valoir',3,'av','valu','5e'],['craindre',3,'av','craint','5e'],
  ['suffire',3,'av','suffi','5e'],['rejoindre',3,'av','rejoint','5e'],
  ['produire',3,'av','produit','5e'],['traduire',3,'av','traduit','5e'],
  // 4e+
  ['perdre',3,'av','perdu','4e'],['vendre',3,'av','vendu','4e'],
  ['attendre',3,'av','attendu','4e'],['entendre',3,'av','entendu','4e'],
  ['répondre',3,'av','répondu','4e'],['défendre',3,'av','défendu','4e'],
  ['répandre',3,'av','répandu','4e'],['confondre',3,'av','confondu','4e'],
  ['conclure',3,'av','conclu','3e'],['inclure',3,'av','inclus','3e'],
  ['exclure',3,'av','exclu','3e'],['dissoudre',3,'av','dissous','3e'],
  ['distraire',3,'av','distrait','2de'],['abstraire',3,'av','abstrait','2de'],
  // ── Verbes supplémentaires ──
  // CP
  ['briller',1,'av','brillé','CP'],['respirer',1,'av','respiré','CP'],['sautiller',1,'av','sautillé','CP'],
  // CE1
  ['balayer',1,'av','balayé','CE1'],['coller',1,'av','collé','CE1'],['colorier',1,'av','colorié','CE1'],
  ['compter',1,'av','compté','CE1'],['gagner',1,'av','gagné','CE1'],['gratter',1,'av','gratté','CE1'],
  ['plier',1,'av','plié','CE1'],['raconter',1,'av','raconté','CE1'],['saluer',1,'av','salué','CE1'],
  ['sourire',3,'av','souri','CE1'],
  // CE2
  ['arroser',1,'av','arrosé','CE2'],['cacher',1,'av','caché','CE2'],['corriger',1,'av','corrigé','CE2'],
  ['décorer',1,'av','décoré','CE2'],['fouiller',1,'av','fouillé','CE2'],['mélanger',1,'av','mélangé','CE2'],
  ['nettoyer',1,'av','nettoyé','CE2'],['ramer',1,'av','ramé','CE2'],['réparer',1,'av','réparé','CE2'],
  ['siffler',1,'av','sifflé','CE2'],['trembler',1,'av','tremblé','CE2'],
  // CM1
  ['avertir',2,'av','averti','CM1'],['conseiller',1,'av','conseillé','CM1'],['douter',1,'av','douté','CM1'],
  ['décrire',3,'av','décrit','CM1'],['exiger',1,'av','exigé','CM1'],['murmurer',1,'av','murmuré','CM1'],
  ['ordonner',1,'av','ordonné','CM1'],['prier',1,'av','prié','CM1'],['réclamer',1,'av','réclamé','CM1'],
  ['saisir',2,'av','saisi','CM1'],['soupirer',1,'av','soupiré','CM1'],['soutenir',3,'av','soutenu','CM1'],
  ['suggérer',1,'av','suggéré','CM1'],
  // CM2
  ['apaiser',1,'av','apaisé','CM2'],['atterrir',2,'et','atterri','CM2'],['cultiver',1,'av','cultivé','CM2'],
  ['décoller',1,'av','décollé','CM2'],['découvrir',3,'av','découvert','CM2'],['fêter',1,'av','fêté','CM2'],
  ['mesurer',1,'av','mesuré','CM2'],['planter',1,'av','planté','CM2'],['remuer',1,'av','remué','CM2'],
  ['réunir',2,'av','réuni','CM2'],['révéler',1,'av','révélé','CM2'],['élaborer',1,'av','élaboré','CM2'],
  // 6e
  ['argumenter',1,'av','argumenté','6e'],['comparer',1,'av','comparé','6e'],['distinguer',1,'av','distingué','6e'],
  ['déduire',3,'av','déduit','6e'],['formuler',1,'av','formulé','6e'],['illustrer',1,'av','illustré','6e'],
  ['interpréter',1,'av','interprété','6e'],['projeter',1,'av','projeté','6e'],['réagir',2,'av','réagi','6e'],
  ['résumer',1,'av','résumé','6e'],['éclairer',1,'av','éclairé','6e'],['évaluer',1,'av','évalué','6e'],
  // 5e
  ['atténuer',1,'av','atténué','5e'],['confronter',1,'av','confronté','5e'],['consolider',1,'av','consolidé','5e'],
  ['contenir',3,'av','contenu','5e'],['optimiser',1,'av','optimisé','5e'],['substituer',1,'av','substitué','5e'],
  ['synthétiser',1,'av','synthétisé','5e'],['valider',1,'av','validé','5e'],['émerger',1,'av','émergé','5e'],
  ['évoquer',1,'av','évoqué','5e'],
  // 4e
  ['amplifier',1,'av','amplifié','4e'],['calibrer',1,'av','calibré','4e'],['incliner',1,'av','incliné','4e'],
  ['négocier',1,'av','négocié','4e'],['réduire',3,'av','réduit','4e'],['répliquer',1,'av','répliqué','4e'],
  ['susciter',1,'av','suscité','4e'],['suspendre',3,'av','suspendu','4e'],
  // 3e
  ['abolir',2,'av','aboli','3e'],['centraliser',1,'av','centralisé','3e'],['converger',1,'av','convergé','3e'],
  ['diviser',1,'av','divisé','3e'],['décentraliser',1,'av','décentralisé','3e'],['fragmenter',1,'av','fragmenté','3e'],
  ['intégrer',1,'av','intégré','3e'],['moduler',1,'av','modulé','3e'],['prédire',3,'av','prédit','3e'],
  ['rationaliser',1,'av','rationalisé','3e'],['rétablir',2,'av','rétabli','3e'],
  // 2de
  ['anticiper',1,'av','anticipé','2de'],['formaliser',1,'av','formalisé','2de'],['harmoniser',1,'av','harmonisé','2de'],
  ['réorienter',1,'av','réorienté','2de'],['subordonner',1,'av','subordonné','2de'],
  // 1re
  ['démultiplier',1,'av','démultiplié','1re'],['hiérarchiser',1,'av','hiérarchisé','1re'],['moderniser',1,'av','modernisé','1re'],
  ['réformer',1,'av','réformé','1re'],
  // Tle
  ['conceptualiser',1,'av','conceptualisé','Tle'],['déployer',1,'av','déployé','Tle'],['institutionnaliser',1,'av','institutionnalisé','Tle'],
  ['neutraliser',1,'av','neutralisé','Tle'],['rétrograder',1,'av','rétrogradé','Tle'],['synchroniser',1,'av','synchronisé','Tle'],
];

// ── Conjugaisons irrégulières ──
const CONJ_IRREG={
  'être':{pres:['suis','es','est','sommes','êtes','sont'],imp:['étais','étais','était','étions','étiez','étaient'],fut:['serai','seras','sera','serons','serez','seront'],cond:['serais','serais','serait','serions','seriez','seraient'],subj:['sois','sois','soit','soyons','soyez','soient']},
  'avoir':{pres:['ai','as','a','avons','avez','ont'],imp:['avais','avais','avait','avions','aviez','avaient'],fut:['aurai','auras','aura','aurons','aurez','auront'],cond:['aurais','aurais','aurait','aurions','auriez','auraient'],subj:['aie','aies','ait','ayons','ayez','aient']},
  'aller':{pres:['vais','vas','va','allons','allez','vont'],imp:['allais','allais','allait','allions','alliez','allaient'],fut:['irai','iras','ira','irons','irez','iront'],cond:['irais','irais','irait','irions','iriez','iraient'],subj:['aille','ailles','aille','allions','alliez','aillent']},
  'faire':{pres:['fais','fais','fait','faisons','faites','font'],imp:['faisais','faisais','faisait','faisions','faisiez','faisaient'],fut:['ferai','feras','fera','ferons','ferez','feront'],cond:['ferais','ferais','ferait','ferions','feriez','feraient'],subj:['fasse','fasses','fasse','fassions','fassiez','fassent']},
  'dire':{pres:['dis','dis','dit','disons','dites','disent'],imp:['disais','disais','disait','disions','disiez','disaient'],fut:['dirai','diras','dira','dirons','direz','diront'],cond:['dirais','dirais','dirait','dirions','diriez','diraient'],subj:['dise','dises','dise','disions','disiez','disent']},
  'prendre':{pres:['prends','prends','prend','prenons','prenez','prennent'],imp:['prenais','prenais','prenait','prenions','preniez','prenaient'],fut:['prendrai','prendras','prendra','prendrons','prendrez','prendront'],cond:['prendrais','prendrais','prendrait','prendrions','prendriez','prendraient'],subj:['prenne','prennes','prenne','prenions','preniez','prennent']},
  'venir':{pres:['viens','viens','vient','venons','venez','viennent'],imp:['venais','venais','venait','venions','veniez','venaient'],fut:['viendrai','viendras','viendra','viendrons','viendrez','viendront'],cond:['viendrais','viendrais','viendrait','viendrions','viendriez','viendraient'],subj:['vienne','viennes','vienne','venions','veniez','viennent']},
  'voir':{pres:['vois','vois','voit','voyons','voyez','voient'],imp:['voyais','voyais','voyait','voyions','voyiez','voyaient'],fut:['verrai','verras','verra','verrons','verrez','verront'],cond:['verrais','verrais','verrait','verrions','verriez','verraient'],subj:['voie','voies','voie','voyions','voyiez','voient']},
  'savoir':{pres:['sais','sais','sait','savons','savez','savent'],imp:['savais','savais','savait','savions','saviez','savaient'],fut:['saurai','sauras','saura','saurons','saurez','sauront'],cond:['saurais','saurais','saurait','saurions','sauriez','sauraient'],subj:['sache','saches','sache','sachions','sachiez','sachent']},
  'pouvoir':{pres:['peux','peux','peut','pouvons','pouvez','peuvent'],imp:['pouvais','pouvais','pouvait','pouvions','pouviez','pouvaient'],fut:['pourrai','pourras','pourra','pourrons','pourrez','pourront'],cond:['pourrais','pourrais','pourrait','pourrions','pourriez','pourraient'],subj:['puisse','puisses','puisse','puissions','puissiez','puissent']},
  'vouloir':{pres:['veux','veux','veut','voulons','voulez','veulent'],imp:['voulais','voulais','voulait','voulions','vouliez','voulaient'],fut:['voudrai','voudras','voudra','voudrons','voudrez','voudront'],cond:['voudrais','voudrais','voudrait','voudrions','voudriez','voudraient'],subj:['veuille','veuilles','veuille','voulions','vouliez','veuillent']},
  'devoir':{pres:['dois','dois','doit','devons','devez','doivent'],imp:['devais','devais','devait','devions','deviez','devaient'],fut:['devrai','devras','devra','devrons','devrez','devront'],cond:['devrais','devrais','devrait','devrions','devriez','devraient'],subj:['doive','doives','doive','devions','deviez','doivent']},
  'mettre':{pres:['mets','mets','met','mettons','mettez','mettent'],imp:['mettais','mettais','mettait','mettions','mettiez','mettaient'],fut:['mettrai','mettras','mettra','mettrons','mettrez','mettront'],cond:['mettrais','mettrais','mettrait','mettrions','mettriez','mettraient'],subj:['mette','mettes','mette','mettions','mettiez','mettent']},
  'partir':{pres:['pars','pars','part','partons','partez','partent'],imp:['partais','partais','partait','partions','partiez','partaient'],fut:['partirai','partiras','partira','partirons','partirez','partiront'],cond:['partirais','partirais','partirait','partirions','partiriez','partiraient'],subj:['parte','partes','parte','partions','partiez','partent']},
  'sortir':{pres:['sors','sors','sort','sortons','sortez','sortent'],imp:['sortais','sortais','sortait','sortions','sortiez','sortaient'],fut:['sortirai','sortiras','sortira','sortirons','sortirez','sortiront'],cond:['sortirais','sortirais','sortirait','sortirions','sortiriez','sortiraient'],subj:['sorte','sortes','sorte','sortions','sortiez','sortent']},
  'tenir':{pres:['tiens','tiens','tient','tenons','tenez','tiennent'],imp:['tenais','tenais','tenait','tenions','teniez','tenaient'],fut:['tiendrai','tiendras','tiendra','tiendrons','tiendrez','tiendront'],cond:['tiendrais','tiendrais','tiendrait','tiendrions','tiendriez','tiendraient'],subj:['tienne','tiennes','tienne','tenions','teniez','tiennent']},
  'recevoir':{pres:['reçois','reçois','reçoit','recevons','recevez','reçoivent'],imp:['recevais','recevais','recevait','recevions','receviez','recevaient'],fut:['recevrai','recevras','recevra','recevrons','recevrez','recevront'],cond:['recevrais','recevrais','recevrait','recevrions','recevriez','recevraient'],subj:['reçoive','reçoives','reçoive','recevions','receviez','reçoivent']},
  'boire':{pres:['bois','bois','boit','buvons','buvez','boivent'],imp:['buvais','buvais','buvait','buvions','buviez','buvaient'],fut:['boirai','boiras','boira','boirons','boirez','boiront'],cond:['boirais','boirais','boirait','boirions','boiriez','boiraient'],subj:['boive','boives','boive','buvions','buviez','boivent']},
  'croire':{pres:['crois','crois','croit','croyons','croyez','croient'],imp:['croyais','croyais','croyait','croyions','croyiez','croyaient'],fut:['croirai','croiras','croira','croirons','croirez','croiront'],cond:['croirais','croirais','croirait','croirions','croiriez','croiraient'],subj:['croie','croies','croie','croyions','croyiez','croient']},
  'écrire':{pres:['écris','écris','écrit','écrivons','écrivez','écrivent'],imp:['écrivais','écrivais','écrivait','écrivions','écriviez','écrivaient'],fut:['écrirai','écriras','écrira','écrirons','écrirez','écriront'],cond:['écrirais','écrirais','écrirait','écririons','écririez','écriraient'],subj:['écrive','écrives','écrive','écrivions','écriviez','écrivent']},
  'lire':{pres:['lis','lis','lit','lisons','lisez','lisent'],imp:['lisais','lisais','lisait','lisions','lisiez','lisaient'],fut:['lirai','liras','lira','lirons','lirez','liront'],cond:['lirais','lirais','lirait','lirions','liriez','liraient'],subj:['lise','lises','lise','lisions','lisiez','lisent']},
  'connaître':{pres:['connais','connais','connaît','connaissons','connaissez','connaissent'],imp:['connaissais','connaissais','connaissait','connaissions','connaissiez','connaissaient'],fut:['connaîtrai','connaîtras','connaîtra','connaîtrons','connaîtrez','connaîtront'],cond:['connaîtrais','connaîtrais','connaîtrait','connaîtrions','connaîtriez','connaîtraient'],subj:['connaisse','connaisses','connaisse','connaissions','connaissiez','connaissent']},
  'suivre':{pres:['suis','suis','suit','suivons','suivez','suivent'],imp:['suivais','suivais','suivait','suivions','suiviez','suivaient'],fut:['suivrai','suivras','suivra','suivrons','suivrez','suivront'],cond:['suivrais','suivrais','suivrait','suivrions','suivriez','suivraient'],subj:['suive','suives','suive','suivions','suiviez','suivent']},
  'vivre':{pres:['vis','vis','vit','vivons','vivez','vivent'],imp:['vivais','vivais','vivait','vivions','viviez','vivaient'],fut:['vivrai','vivras','vivra','vivrons','vivrez','vivront'],cond:['vivrais','vivrais','vivrait','vivrions','vivriez','vivraient'],subj:['vive','vives','vive','vivions','viviez','vivent']},
  'courir':{pres:['cours','cours','court','courons','courez','courent'],imp:['courais','courais','courait','courions','couriez','couraient'],fut:['courrai','courras','courra','courrons','courrez','courront'],cond:['courrais','courrais','courrait','courrions','courriez','courraient'],subj:['coure','coures','coure','courions','couriez','courent']},
  'ouvrir':{pres:['ouvre','ouvres','ouvre','ouvrons','ouvrez','ouvrent'],imp:['ouvrais','ouvrais','ouvrait','ouvrions','ouvriez','ouvraient'],fut:['ouvrirai','ouvriras','ouvrira','ouvrirons','ouvrirez','ouvriront'],cond:['ouvrirais','ouvrirais','ouvrirait','ouvririons','ouvririez','ouvriraient'],subj:['ouvre','ouvres','ouvre','ouvrions','ouvriez','ouvrent']},
  'mourir':{pres:['meurs','meurs','meurt','mourons','mourez','meurent'],imp:['mourais','mourais','mourait','mourions','mouriez','mouraient'],fut:['mourrai','mourras','mourra','mourrons','mourrez','mourront'],cond:['mourrais','mourrais','mourrait','mourrions','mourriez','mourraient'],subj:['meure','meures','meure','mourions','mouriez','meurent']},
  'valoir':{pres:['vaux','vaux','vaut','valons','valez','valent'],imp:['valais','valais','valait','valions','valiez','valaient'],fut:['vaudrai','vaudras','vaudra','vaudrons','vaudrez','vaudront'],cond:['vaudrais','vaudrais','vaudrait','vaudrions','vaudriez','vaudraient'],subj:['vaille','vailles','vaille','valions','valiez','vaillent']},
  'craindre':{pres:['crains','crains','craint','craignons','craignez','craignent'],imp:['craignais','craignais','craignait','craignions','craigniez','craignaient'],fut:['craindrai','craindras','craindra','craindrons','craindrez','craindront'],cond:['craindrais','craindrais','craindrait','craindrions','craindriez','craindraient'],subj:['craigne','craignes','craigne','craignions','craigniez','craignent']},
  'perdre':{pres:['perds','perds','perd','perdons','perdez','perdent'],imp:['perdais','perdais','perdait','perdions','perdiez','perdaient'],fut:['perdrai','perdras','perdra','perdrons','perdrez','perdront'],cond:['perdrais','perdrais','perdrait','perdrions','perdriez','perdraient'],subj:['perde','perdes','perde','perdions','perdiez','perdent']},
  'vendre':{pres:['vends','vends','vend','vendons','vendez','vendent'],imp:['vendais','vendais','vendait','vendions','vendiez','vendaient'],fut:['vendrai','vendras','vendra','vendrons','vendrez','vendront'],cond:['vendrais','vendrais','vendrait','vendrions','vendriez','vendraient'],subj:['vende','vendes','vende','vendions','vendiez','vendent']},
  'attendre':{pres:['attends','attends','attend','attendons','attendez','attendent'],imp:['attendais','attendais','attendait','attendions','attendiez','attendaient'],fut:['attendrai','attendras','attendra','attendrons','attendrez','attendront'],cond:['attendrais','attendrais','attendrait','attendrions','attendriez','attendraient'],subj:['attende','attendes','attende','attendions','attendiez','attendent']},
  'répondre':{pres:['réponds','réponds','répond','répondons','répondez','répondent'],imp:['répondais','répondais','répondait','répondions','répondiez','répondaient'],fut:['répondrai','répondras','répondra','répondrons','répondrez','répondront'],cond:['répondrais','répondrais','répondrait','répondrions','répondriez','répondraient'],subj:['réponde','répondes','réponde','répondions','répondiez','répondent']},
  'appeler':{pres:['appelle','appelles','appelle','appelons','appelez','appellent'],imp:['appelais','appelais','appelait','appelions','appeliez','appelaient'],fut:['appellerai','appelleras','appellera','appellerons','appellerez','appelleront'],cond:['appellerais','appellerais','appellerait','appellerions','appelleriez','appelleraient'],subj:['appelle','appelles','appelle','appelions','appeliez','appellent']},
  'lever':{pres:['lève','lèves','lève','levons','levez','lèvent'],imp:['levais','levais','levait','levions','leviez','levaient'],fut:['lèverai','lèveras','lèvera','lèverons','lèverez','lèveront'],cond:['lèverais','lèverais','lèverait','lèverions','lèveriez','lèveraient'],subj:['lève','lèves','lève','levions','leviez','lèvent']},
  'battre':{pres:['bats','bats','bat','battons','battez','battent'],imp:['battais','battais','battait','battions','battiez','battaient'],fut:['battrai','battras','battra','battrons','battrez','battront'],cond:['battrais','battrais','battrait','battrions','battriez','battraient'],subj:['batte','battes','batte','battions','battiez','battent']},
  'mentir':{pres:['mens','mens','ment','mentons','mentez','mentent'],imp:['mentais','mentais','mentait','mentions','mentiez','mentaient'],fut:['mentirai','mentiras','mentira','mentirons','mentirez','mentiront'],cond:['mentirais','mentirais','mentirait','mentirions','mentiriez','mentiraient'],subj:['mente','mentes','mente','mentions','mentiez','mentent']},
  'peindre':{pres:['peins','peins','peint','peignons','peignez','peignent'],imp:['peignais','peignais','peignait','peignions','peigniez','peignaient'],fut:['peindrai','peindras','peindra','peindrons','peindrez','peindront'],cond:['peindrais','peindrais','peindrait','peindrions','peindriez','peindraient'],subj:['peigne','peignes','peigne','peignions','peigniez','peignent']},
  'produire':{pres:['produis','produis','produit','produisons','produisez','produisent'],imp:['produisais','produisais','produisait','produisions','produisiez','produisaient'],fut:['produirai','produiras','produira','produirons','produirez','produiront'],cond:['produirais','produirais','produirait','produirions','produiriez','produiraient'],subj:['produise','produises','produise','produisions','produisiez','produisent']},
  'résoudre':{pres:['résous','résous','résout','résolvons','résolvez','résolvent'],imp:['résolvais','résolvais','résolvait','résolvions','résolviez','résolvaient'],fut:['résoudrai','résoudras','résoudra','résoudrons','résoudrez','résoudront'],cond:['résoudrais','résoudrais','résoudrait','résoudrions','résoudriez','résoudraient'],subj:['résolve','résolves','résolve','résolvions','résolviez','résolvent']},

  'paraître':{pres:['parais','parais','paraît','paraissons','paraissez','paraissent'],imp:['paraissais','paraissais','paraissait','paraissions','paraissiez','paraissaient'],fut:['paraîtrai','paraîtras','paraîtra','paraîtrons','paraîtrez','paraîtront'],cond:['paraîtrais','paraîtrais','paraîtrait','paraîtrions','paraîtriez','paraîtraient'],subj:['paraisse','paraisses','paraisse','paraissions','paraissiez','paraissent']},
  'apparaître':{pres:['apparais','apparais','apparaît','apparaissons','apparaissez','apparaissent'],imp:['apparaissais','apparaissais','apparaissait','apparaissions','apparaissiez','apparaissaient'],fut:['apparaîtrai','apparaîtras','apparaîtra','apparaîtrons','apparaîtrez','apparaîtront'],cond:['apparaîtrais','apparaîtrais','apparaîtrait','apparaîtrions','apparaîtriez','apparaîtraient'],subj:['apparaisse','apparaisses','apparaisse','apparaissions','apparaissiez','apparaissent']},
  'promettre':{pres:['promets','promets','promet','promettons','promettez','promettent'],imp:['promettais','promettais','promettait','promettions','promettiez','promettaient'],fut:['promettrai','promettras','promettra','promettrons','promettrez','promettront'],cond:['promettrais','promettrais','promettrait','promettrions','promettriez','promettraient'],subj:['promette','promettes','promette','promettions','promettiez','promettent']},
  'permettre':{pres:['permets','permets','permet','permettons','permettez','permettent'],imp:['permettais','permettais','permettait','permettions','permettiez','permettaient'],fut:['permettrai','permettras','permettra','permettrons','permettrez','permettront'],cond:['permettrais','permettrais','permettrait','permettrions','permettriez','permettraient'],subj:['permette','permettes','permette','permettions','permettiez','permettent']},
  'comprendre':{pres:['comprends','comprends','comprend','comprenons','comprenez','comprennent'],imp:['comprenais','comprenais','comprenait','comprenions','compreniez','comprenaient'],fut:['comprendrai','comprendras','comprendra','comprendrons','comprendrez','comprendront'],cond:['comprendrais','comprendrais','comprendrait','comprendrions','comprendriez','comprendraient'],subj:['comprenne','comprennes','comprenne','comprenions','compreniez','comprennent']},
  'apprendre':{pres:['apprends','apprends','apprend','apprenons','apprenez','apprennent'],imp:['apprenais','apprenais','apprenait','apprenions','appreniez','apprenaient'],fut:['apprendrai','apprendras','apprendra','apprendrons','apprendrez','apprendront'],cond:['apprendrais','apprendrais','apprendrait','apprendrions','apprendriez','apprendraient'],subj:['apprenne','apprennes','apprenne','apprenions','appreniez','apprennent']},
  'souffrir':{pres:['souffre','souffres','souffre','souffrons','souffrez','souffrent'],imp:['souffrais','souffrais','souffrait','souffrions','souffriez','souffraient'],fut:['souffrirai','souffriras','souffrira','souffrirons','souffrirez','souffriront'],cond:['souffrirais','souffrirais','souffrirait','souffririons','souffririez','souffriraient'],subj:['souffre','souffres','souffre','souffrions','souffriez','souffrent']},
  'offrir':{pres:['offre','offres','offre','offrons','offrez','offrent'],imp:['offrais','offrais','offrait','offrions','offriez','offraient'],fut:['offrirai','offriras','offrira','offrirons','offrirez','offriront'],cond:['offrirais','offrirais','offrirait','offririons','offririez','offriraient'],subj:['offre','offres','offre','offrions','offriez','offrent']},
  'dormir':{pres:['dors','dors','dort','dormons','dormez','dorment'],imp:['dormais','dormais','dormait','dormions','dormiez','dormaient'],fut:['dormirai','dormiras','dormira','dormirons','dormirez','dormiront'],cond:['dormirais','dormirais','dormirait','dormirions','dormiriez','dormiraient'],subj:['dorme','dormes','dorme','dormions','dormiez','dorment']},
  'sentir':{pres:['sens','sens','sent','sentons','sentez','sentent'],imp:['sentais','sentais','sentait','sentions','sentiez','sentaient'],fut:['sentirai','sentiras','sentira','sentirons','sentirez','sentiront'],cond:['sentirais','sentirais','sentirait','sentirions','sentiriez','sentiraient'],subj:['sente','sentes','sente','sentions','sentiez','sentent']},
  'fuir':{pres:['fuis','fuis','fuit','fuyons','fuyez','fuient'],imp:['fuyais','fuyais','fuyait','fuyions','fuyiez','fuyaient'],fut:['fuirai','fuiras','fuira','fuirons','fuirez','fuiront'],cond:['fuirais','fuirais','fuirait','fuirions','fuiriez','fuiraient'],subj:['fuie','fuies','fuie','fuyions','fuyiez','fuient']},
  'élire':{pres:['élis','élis','élit','élisons','élisez','élisent'],imp:['élisais','élisais','élisait','élisions','élisiez','élisaient'],fut:['élirai','éliras','élira','élirons','élirez','éliront'],cond:['élirais','élirais','élirait','élirions','éliriez','éliraient'],subj:['élise','élises','élise','élisions','élisiez','élisent']},
  'acquérir':{pres:['acquiers','acquiers','acquiert','acquérons','acquérez','acquièrent'],imp:['acquérais','acquérais','acquérait','acquérions','acquériez','acquéraient'],fut:['acquerrai','acquerras','acquerra','acquerrons','acquerrez','acquerront'],cond:['acquerrais','acquerrais','acquerrait','acquerrions','acquerriez','acquerraient'],subj:['acquière','acquières','acquière','acquérions','acquériez','acquièrent']},
  'vaincre':{pres:['vaincs','vaincs','vainc','vainquons','vainquez','vainquent'],imp:['vainquais','vainquais','vainquait','vainquions','vainquiez','vainquaient'],fut:['vaincrai','vaincras','vaincra','vaincrons','vaincrez','vaincront'],cond:['vaincrais','vaincrais','vaincrait','vaincrions','vaincriez','vaincraient'],subj:['vainque','vainques','vainque','vainquions','vainquiez','vainquent']},
  'rire':{pres:['ris','ris','rit','rions','riez','rient'],imp:['riais','riais','riait','riions','riiez','riaient'],fut:['rirai','riras','rira','rirons','rirez','riront'],cond:['rirais','rirais','rirait','ririons','ririez','riraient'],subj:['rie','ries','rie','riions','riiez','rient']},
  'distraire':{pres:['distrais','distrais','distrait','distrayons','distrayez','distraient'],imp:['distrayais','distrayais','distrayait','distrayions','distrayiez','distrayaient'],fut:['distrairai','distrairas','distraira','distrairons','distrairez','distrairont'],cond:['distrairais','distrairais','distrairait','distrairions','distrairiez','distrairaient'],subj:['distraie','distraies','distraie','distrayions','distrayiez','distraient']},
  'abstraire':{pres:['abstrais','abstrais','abstrait','abstrayons','abstrayez','abstraient'],imp:['abstrayais','abstrayais','abstrayait','abstrayions','abstrayiez','abstrayaient'],fut:['abstrairai','abstrairas','abstraira','abstrairons','abstrairez','abstrairont'],cond:['abstrairais','abstrairais','abstrairait','abstrairions','abstrairiez','abstrairaient'],subj:['abstraie','abstraies','abstraie','abstrayions','abstrayiez','abstraient']},
  'descendre':{pres:['descends','descends','descend','descendons','descendez','descendent'],imp:['descendais','descendais','descendait','descendions','descendiez','descendaient'],fut:['descendrai','descendras','descendra','descendrons','descendrez','descendront'],cond:['descendrais','descendrais','descendrait','descendrions','descendriez','descendraient'],subj:['descende','descendes','descende','descendions','descendiez','descendent']},
  'servir':{pres:['sers','sers','sert','servons','servez','servent'],imp:['servais','servais','servait','servions','serviez','servaient'],fut:['servirai','serviras','servira','servirons','servirez','serviront'],cond:['servirais','servirais','servirait','servirions','serviriez','serviraient'],subj:['serve','serves','serve','servions','serviez','servent']},
  'cueillir':{pres:['cueille','cueilles','cueille','cueillons','cueillez','cueillent'],imp:['cueillais','cueillais','cueillait','cueillions','cueilliez','cueillaient'],fut:['cueillerai','cueilleras','cueillera','cueillerons','cueillerez','cueilleront'],cond:['cueillerais','cueillerais','cueillerait','cueillerions','cueilleriez','cueilleraient'],subj:['cueille','cueilles','cueille','cueillions','cueilliez','cueillent']},
  'joindre':{pres:['joins','joins','joint','joignons','joignez','joignent'],imp:['joignais','joignais','joignait','joignions','joigniez','joignaient'],fut:['joindrai','joindras','joindra','joindrons','joindrez','joindront'],cond:['joindrais','joindrais','joindrait','joindrions','joindriez','joindraient'],subj:['joigne','joignes','joigne','joignions','joigniez','joignent']},
  'conduire':{pres:['conduis','conduis','conduit','conduisons','conduisez','conduisent'],imp:['conduisais','conduisais','conduisait','conduisions','conduisiez','conduisaient'],fut:['conduirai','conduiras','conduira','conduirons','conduirez','conduiront'],cond:['conduirais','conduirais','conduirait','conduirions','conduiriez','conduiraient'],subj:['conduise','conduises','conduise','conduisions','conduisiez','conduisent']},
  'construire':{pres:['construis','construis','construit','construisons','construisez','construisent'],imp:['construisais','construisais','construisait','construisions','construisiez','construisaient'],fut:['construirai','construiras','construira','construirons','construirez','construiront'],cond:['construirais','construirais','construirait','construirions','construiriez','construiraient'],subj:['construise','construises','construise','construisions','construisiez','construisent']},
  'naître':{pres:['nais','nais','naît','naissons','naissez','naissent'],imp:['naissais','naissais','naissait','naissions','naissiez','naissaient'],fut:['naîtrai','naîtras','naîtra','naîtrons','naîtrez','naîtront'],cond:['naîtrais','naîtrais','naîtrait','naîtrions','naîtriez','naîtraient'],subj:['naisse','naisses','naisse','naissions','naissiez','naissent']},
  'suffire':{pres:['suffis','suffis','suffit','suffisons','suffisez','suffisent'],imp:['suffisais','suffisais','suffisait','suffisions','suffisiez','suffisaient'],fut:['suffirai','suffiras','suffira','suffirons','suffirez','suffiront'],cond:['suffirais','suffirais','suffirait','suffirions','suffiriez','suffiraient'],subj:['suffise','suffises','suffise','suffisions','suffisiez','suffisent']},
  'rejoindre':{pres:['rejoins','rejoins','rejoint','rejoignons','rejoignez','rejoignent'],imp:['rejoignais','rejoignais','rejoignait','rejoignions','rejoigniez','rejoignaient'],fut:['rejoindrai','rejoindras','rejoindra','rejoindrons','rejoindrez','rejoindront'],cond:['rejoindrais','rejoindrais','rejoindrait','rejoindrions','rejoindriez','rejoindraient'],subj:['rejoigne','rejoignes','rejoigne','rejoignions','rejoigniez','rejoignent']},
  'traduire':{pres:['traduis','traduis','traduit','traduisons','traduisez','traduisent'],imp:['traduisais','traduisais','traduisait','traduisions','traduisiez','traduisaient'],fut:['traduirai','traduiras','traduira','traduirons','traduirez','traduiront'],cond:['traduirais','traduirais','traduirait','traduirions','traduiriez','traduiraient'],subj:['traduise','traduises','traduise','traduisions','traduisiez','traduisent']},
  'entendre':{pres:['entends','entends','entend','entendons','entendez','entendent'],imp:['entendais','entendais','entendait','entendions','entendiez','entendaient'],fut:['entendrai','entendras','entendra','entendrons','entendrez','entendront'],cond:['entendrais','entendrais','entendrait','entendrions','entendriez','entendraient'],subj:['entende','entendes','entende','entendions','entendiez','entendent']},
  'défendre':{pres:['défends','défends','défend','défendons','défendez','défendent'],imp:['défendais','défendais','défendait','défendions','défendiez','défendaient'],fut:['défendrai','défendras','défendra','défendrons','défendrez','défendront'],cond:['défendrais','défendrais','défendrait','défendrions','défendriez','défendraient'],subj:['défende','défendes','défende','défendions','défendiez','défendent']},
  'répandre':{pres:['répands','répands','répand','répandons','répandez','répandent'],imp:['répandais','répandais','répandait','répandions','répandiez','répandaient'],fut:['répandrai','répandras','répandra','répandrons','répandrez','répandront'],cond:['répandrais','répandrais','répandrait','répandrions','répandriez','répandraient'],subj:['répande','répandes','répande','répandions','répandiez','répandent']},
  'confondre':{pres:['confonds','confonds','confond','confondons','confondez','confondent'],imp:['confondais','confondais','confondait','confondions','confondiez','confondaient'],fut:['confondrai','confondras','confondra','confondrons','confondrez','confondront'],cond:['confondrais','confondrais','confondrait','confondrions','confondriez','confondraient'],subj:['confonde','confondes','confonde','confondions','confondiez','confondent']},
  'conclure':{pres:['conclus','conclus','conclut','concluons','concluez','concluent'],imp:['concluais','concluais','concluait','concluions','concluiez','concluaient'],fut:['conclurai','concluras','conclura','conclurons','conclurez','concluront'],cond:['conclurais','conclurais','conclurait','conclurions','concluriez','concluraient'],subj:['conclue','conclues','conclue','concluions','concluiez','concluent']},
  'inclure':{pres:['inclus','inclus','inclut','incluons','incluez','incluent'],imp:['incluais','incluais','incluait','incluions','incluiez','incluaient'],fut:['inclurai','incluras','inclura','inclurons','inclurez','incluront'],cond:['inclurais','inclurais','inclurait','inclurions','incluriez','incluraient'],subj:['inclue','inclues','inclue','incluions','incluiez','incluent']},
  'exclure':{pres:['exclus','exclus','exclut','excluons','excluez','excluent'],imp:['excluais','excluais','excluait','excluions','excluiez','excluaient'],fut:['exclurai','excluras','exclura','exclurons','exclurez','excluront'],cond:['exclurais','exclurais','exclurait','exclurions','excluriez','excluraient'],subj:['exclue','exclues','exclue','excluions','excluiez','excluent']},
  'dissoudre':{pres:['dissous','dissous','dissout','dissolvons','dissolvez','dissolvent'],imp:['dissolvais','dissolvais','dissolvait','dissolvions','dissolviez','dissolvaient'],fut:['dissoudrai','dissoudras','dissoudra','dissoudrons','dissoudrez','dissoudront'],cond:['dissoudrais','dissoudrais','dissoudrait','dissoudrions','dissoudriez','dissoudraient'],subj:['dissolve','dissolves','dissolve','dissolvions','dissolviez','dissolvent']},
  'sourire':{pres:['souris','souris','sourit','sourions','souriez','sourient'],imp:['souriais','souriais','souriait','souriions','souriiez','souriaient'],fut:['sourirai','souriras','sourira','sourirons','sourirez','souriront'],cond:['sourirais','sourirais','sourirait','souririons','souririez','souriraient'],subj:['sourie','souries','sourie','souriions','souriiez','sourient']},
  'décrire':{pres:['décris','décris','décrit','décrivons','décrivez','décrivent'],imp:['décrivais','décrivais','décrivait','décrivions','décriviez','décrivaient'],fut:['décrirai','décriras','décrira','décrirons','décrirez','décriront'],cond:['décrirais','décrirais','décrirait','décririons','décririez','décriraient'],subj:['décrive','décrives','décrive','décrivions','décriviez','décrivent']},
  'soutenir':{pres:['soutiens','soutiens','soutient','soutenons','soutenez','soutiennent'],imp:['soutenais','soutenais','soutenait','soutenions','souteniez','soutenaient'],fut:['soutiendrai','soutiendras','soutiendra','soutiendrons','soutiendrez','soutiendront'],cond:['soutiendrais','soutiendrais','soutiendrait','soutiendrions','soutien​driez','soutiendraient'],subj:['soutienne','soutiennes','soutienne','soutenions','souteniez','soutiennent']},
  'découvrir':{pres:['découvre','découvres','découvre','découvrons','découvrez','découvrent'],imp:['découvrais','découvrais','découvrait','découvrions','découvriez','découvraient'],fut:['découvrirai','découvriras','découvrira','découvrirons','découvrirez','découvriront'],cond:['découvrirais','découvrirais','découvrirait','découvririons','découvririez','découvriraient'],subj:['découvre','découvres','découvre','découvrions','découvriez','découvrent']},
  'déduire':{pres:['déduis','déduis','déduit','déduisons','déduisez','déduisent'],imp:['déduisais','déduisais','déduisait','déduisions','déduisiez','déduisaient'],fut:['déduirai','déduiras','déduira','déduirons','déduirez','déduiront'],cond:['déduirais','déduirais','déduirait','déduirions','déduiriez','déduiraient'],subj:['déduise','déduises','déduise','déduisions','déduisiez','déduisent']},
  'contenir':{pres:['contiens','contiens','contient','contenons','contenez','contiennent'],imp:['contenais','contenais','contenait','contenions','conteniez','contenaient'],fut:['contiendrai','contiendras','contiendra','contiendrons','contiendrez','contiendront'],cond:['contiendrais','contiendrais','contiendrait','contiendrions','contiendriez','contiendraient'],subj:['contienne','contiennes','contienne','contenions','conteniez','contiennent']},
  'réduire':{pres:['réduis','réduis','réduit','réduisons','réduisez','réduisent'],imp:['réduisais','réduisais','réduisait','réduisions','réduisiez','réduisaient'],fut:['réduirai','réduiras','réduira','réduirons','réduirez','réduiront'],cond:['réduirais','réduirais','réduirait','réduirions','réduiriez','réduiraient'],subj:['réduise','réduises','réduise','réduisions','réduisiez','réduisent']},
  'suspendre':{pres:['suspends','suspends','suspend','suspendons','suspendez','suspendent'],imp:['suspendais','suspendais','suspendait','suspendions','suspendiez','suspendaient'],fut:['suspendrai','suspendras','suspendra','suspendrons','suspendrez','suspendront'],cond:['suspendrais','suspendrais','suspendrait','suspendrions','suspendriez','suspendraient'],subj:['suspende','suspendes','suspende','suspendions','suspendiez','suspendent']},
  'prédire':{pres:['prédis','prédis','prédit','prédisons','prédisez','prédisent'],imp:['prédisais','prédisais','prédisait','prédisions','prédi​siez','prédisaient'],fut:['prédirai','prédiras','prédira','prédirons','prédirez','prédiront'],cond:['prédirais','prédirais','prédirait','prédirions','prédiriez','prédiraient'],subj:['prédise','prédises','prédise','prédisions','prédi​siez','prédisent']},
  'plaire':{pres:['plais','plais','plaît','plaisons','plaisez','plaisent'],imp:['plaisais','plaisais','plaisait','plaisions','plaisiez','plaisaient'],fut:['plairai','plairas','plaira','plairons','plairez','plairont'],cond:['plairais','plairais','plairait','plairions','plairiez','plairaient'],subj:['plaise','plaises','plaise','plaisions','plaisiez','plaisent']},
};

// ── Niveaux ──
