// ══════════════════════════════════════════════════
// FRANÇAIS POSÉ — data.js  (version enrichie)
// Règle des distracteurs : toujours des variantes
// du même mot ou des leurres sémantiquement proches.
// Jamais un mot venu d'une autre entrée au hasard.
// ══════════════════════════════════════════════════

// ── Verbes ── [infinitif, groupe, auxiliaire, participe_passé, niveau_min]
const VERB_LIST=[
  // CP
  ['être',3,'et','été','CP'],['avoir',3,'av','eu','CP'],
  // CE1
  ['aimer',1,'av','aimé','CE1'],['parler',1,'av','parlé','CE1'],
  ['chanter',1,'av','chanté','CE1'],['danser',1,'av','dansé','CE1'],
  ['jouer',1,'av','joué','CE1'],['regarder',1,'av','regardé','CE1'],
  ['écouter',1,'av','écouté','CE1'],['travailler',1,'av','travaillé','CE1'],
  ['chercher',1,'av','cherché','CE1'],['trouver',1,'av','trouvé','CE1'],
  ['donner',1,'av','donné','CE1'],['penser',1,'av','pensé','CE1'],
  ['rester',1,'et','resté','CE1'],['arriver',1,'et','arrivé','CE1'],
  ['montrer',1,'av','montré','CE1'],['tourner',1,'av','tourné','CE1'],
  ['porter',1,'av','porté','CE1'],['manger',1,'av','mangé','CE1'],
  ['dessiner',1,'av','dessiné','CE1'],['entrer',1,'et','entré','CE1'],
  ['tomber',1,'et','tombé','CE1'],['monter',1,'et','monté','CE1'],
  ['marcher',1,'av','marché','CE1'],['sauter',1,'av','sauté','CE1'],
  ['crier',1,'av','crié','CE1'],['pleurer',1,'av','pleuré','CE1'],
  ['couper',1,'av','coupé','CE1'],['poser',1,'av','posé','CE1'],
  ['laver',1,'av','lavé','CE1'],['fermer',1,'av','fermé','CE1'],
  ['oublier',1,'av','oublié','CE1'],['décider',1,'av','décidé','CE1'],
  ['habiter',1,'av','habité','CE1'],['aider',1,'av','aidé','CE1'],
  ['acheter',1,'av','acheté','CE1'],['appeler',1,'av','appelé','CE1'],
  // CE2
  ['commencer',1,'av','commencé','CE2'],['bouger',1,'av','bougé','CE2'],
  ['nager',1,'av','nagé','CE2'],['rentrer',1,'et','rentré','CE2'],
  ['passer',1,'av','passé','CE2'],['lever',1,'av','levé','CE2'],
  ['ranger',1,'av','rangé','CE2'],['choisir',2,'av','choisi','CE2'],
  ['finir',2,'av','fini','CE2'],['grandir',2,'et','grandi','CE2'],
  ['préparer',1,'av','préparé','CE2'],['expliquer',1,'av','expliqué','CE2'],
  ['traverser',1,'av','traversé','CE2'],['rencontrer',1,'av','rencontré','CE2'],
  ['lancer',1,'av','lancé','CE2'],['avancer',1,'av','avancé','CE2'],
  ['reculer',1,'av','reculé','CE2'],['grimper',1,'av','grimpé','CE2'],
  ['glisser',1,'et','glissé','CE2'],['plonger',1,'av','plongé','CE2'],
  // CM1
  ['espérer',1,'av','espéré','CM1'],['répéter',1,'av','répété','CM1'],
  ['voyager',1,'av','voyagé','CM1'],['rougir',2,'av','rougi','CM1'],
  ['réfléchir',2,'av','réfléchi','CM1'],['réussir',2,'av','réussi','CM1'],
  ['obéir',2,'av','obéi','CM1'],['nourrir',2,'av','nourri','CM1'],
  ['punir',2,'av','puni','CM1'],['faire',3,'av','fait','CM1'],
  ['dire',3,'av','dit','CM1'],['prendre',3,'av','pris','CM1'],
  ['venir',3,'et','venu','CM1'],['voir',3,'av','vu','CM1'],
  ['savoir',3,'av','su','CM1'],['pouvoir',3,'av','pu','CM1'],
  ['vouloir',3,'av','voulu','CM1'],['devoir',3,'av','dû','CM1'],
  ['mettre',3,'av','mis','CM1'],['partir',3,'et','parti','CM1'],
  ['sortir',3,'et','sorti','CM1'],['aller',3,'et','allé','CM1'],
  ['rappeler',1,'av','rappelé','CM1'],['améliorer',1,'av','amélioré','CM1'],
  ['utiliser',1,'av','utilisé','CM1'],['terminer',1,'av','terminé','CM1'],
  ['observer',1,'av','observé','CM1'],['installer',1,'av','installé','CM1'],
  ['remplacer',1,'av','remplacé','CM1'],['accepter',1,'av','accepté','CM1'],
  // CM2
  ['agir',2,'av','agi','CM2'],['établir',2,'av','établi','CM2'],
  ['tenir',3,'av','tenu','CM2'],['recevoir',3,'av','reçu','CM2'],
  ['boire',3,'av','bu','CM2'],['croire',3,'av','cru','CM2'],
  ['écrire',3,'av','écrit','CM2'],['lire',3,'av','lu','CM2'],
  ['descendre',3,'et','descendu','CM2'],['résoudre',3,'av','résolu','CM2'],
  ['remplir',2,'av','rempli','CM2'],['subir',2,'av','subi','CM2'],
  ['fournir',2,'av','fourni','CM2'],['accomplir',2,'av','accompli','CM2'],
  // 6e
  ['connaître',3,'av','connu','6e'],['suivre',3,'av','suivi','6e'],
  ['vivre',3,'av','vécu','6e'],['courir',3,'av','couru','6e'],
  ['ouvrir',3,'av','ouvert','6e'],['offrir',3,'av','offert','6e'],
  ['sentir',3,'av','senti','6e'],['dormir',3,'av','dormi','6e'],
  ['servir',3,'av','servi','6e'],['rire',3,'av','ri','6e'],
  ['plaire',3,'av','plu','6e'],['cueillir',3,'av','cueilli','6e'],
  ['mentir',3,'av','menti','6e'],['battre',3,'av','battu','6e'],
  ['peindre',3,'av','peint','6e'],['joindre',3,'av','joint','6e'],
  // 5e
  ['conduire',3,'av','conduit','5e'],['construire',3,'av','construit','5e'],
  ['naître',3,'et','né','5e'],['mourir',3,'et','mort','5e'],
  ['valoir',3,'av','valu','5e'],['craindre',3,'av','craint','5e'],
  ['suffire',3,'av','suffi','5e'],['rejoindre',3,'av','rejoint','5e'],
  ['produire',3,'av','produit','5e'],['traduire',3,'av','traduit','5e'],
  // 4e+
  ['perdre',3,'av','perdu','4e'],['vendre',3,'av','vendu','4e'],
  ['attendre',3,'av','attendu','4e'],['entendre',3,'av','entendu','4e'],
  ['répondre',3,'av','répondu','4e'],['défendre',3,'av','défendu','4e'],
  ['répandre',3,'av','répandu','4e'],['confondre',3,'av','confondu','4e'],
  ['conclure',3,'av','conclu','3e'],['inclure',3,'av','inclus','3e'],
  ['exclure',3,'av','exclu','3e'],['dissoudre',3,'av','dissous','3e'],
  ['distraire',3,'av','distrait','2de'],['abstraire',3,'av','abstrait','2de'],
];

// ── Conjugaisons irrégulières ──
const CONJ_IRREG={
  'être':{pres:['suis','es','est','sommes','êtes','sont'],imp:['étais','étais','était','étions','étiez','étaient'],fut:['serai','seras','sera','serons','serez','seront'],cond:['serais','serais','serait','serions','seriez','seraient'],subj:['sois','sois','soit','soyons','soyez','soient']},
  'avoir':{pres:['ai','as','a','avons','avez','ont'],imp:['avais','avais','avait','avions','aviez','avaient'],fut:['aurai','auras','aura','aurons','aurez','auront'],cond:['aurais','aurais','aurait','aurions','auriez','auraient'],subj:['aie','aies','ait','ayons','ayez','aient']},
  'aller':{pres:['vais','vas','va','allons','allez','vont'],imp:['allais','allais','allait','allions','alliez','allaient'],fut:['irai','iras','ira','irons','irez','iront'],cond:['irais','irais','irait','irions','iriez','iraient'],subj:['aille','ailles','aille','allions','alliez','aillent']},
  'faire':{pres:['fais','fais','fait','faisons','faites','font'],imp:['faisais','faisais','faisait','faisions','faisiez','faisaient'],fut:['ferai','feras','fera','ferons','ferez','feront'],cond:['ferais','ferais','ferait','ferions','feriez','feraient'],subj:['fasse','fasses','fasse','fassions','fassiez','fassent']},
  'dire':{pres:['dis','dis','dit','disons','dites','disent'],imp:['disais','disais','disait','disions','disiez','disaient'],fut:['dirai','diras','dira','dirons','direz','diront'],cond:['dirais','dirais','dirait','dirions','diriez','diraient'],subj:['dise','dises','dise','disions','disiez','disent']},
  'prendre':{pres:['prends','prends','prend','prenons','prenez','prennent'],imp:['prenais','prenais','prenait','prenions','preniez','prenaient'],fut:['prendrai','prendras','prendra','prendrons','prendrez','prendront'],cond:['prendrais','prendrais','prendrait','prendrions','prendriez','prendraient'],subj:['prenne','prennes','prenne','prenions','preniez','prennent']},
  'venir':{pres:['viens','viens','vient','venons','venez','viennent'],imp:['venais','venais','venait','venions','veniez','venaient'],fut:['viendrai','viendras','viendra','viendrons','viendrez','viendront'],cond:['viendrais','viendrais','viendrait','viendrions','viendriez','viendraient'],subj:['vienne','viennes','vienne','venions','veniez','viennent']},
  'voir':{pres:['vois','vois','voit','voyons','voyez','voient'],imp:['voyais','voyais','voyait','voyions','voyiez','voyaient'],fut:['verrai','verras','verra','verrons','verrez','verront'],cond:['verrais','verrais','verrait','verrions','verriez','verraient'],subj:['voie','voies','voie','voyions','voyiez','voient']},
  'savoir':{pres:['sais','sais','sait','savons','savez','savent'],imp:['savais','savais','savait','savions','saviez','savaient'],fut:['saurai','sauras','saura','saurons','saurez','sauront'],cond:['saurais','saurais','saurait','saurions','sauriez','sauraient'],subj:['sache','saches','sache','sachions','sachiez','sachent']},
  'pouvoir':{pres:['peux','peux','peut','pouvons','pouvez','peuvent'],imp:['pouvais','pouvais','pouvait','pouvions','pouviez','pouvaient'],fut:['pourrai','pourras','pourra','pourrons','pourrez','pourront'],cond:['pourrais','pourrais','pourrait','pourrions','pourriez','pourraient'],subj:['puisse','puisses','puisse','puissions','puissiez','puissent']},
  'vouloir':{pres:['veux','veux','veut','voulons','voulez','veulent'],imp:['voulais','voulais','voulait','voulions','vouliez','voulaient'],fut:['voudrai','voudras','voudra','voudrons','voudrez','voudront'],cond:['voudrais','voudrais','voudrait','voudrions','voudriez','voudraient'],subj:['veuille','veuilles','veuille','voulions','vouliez','veuillent']},
  'devoir':{pres:['dois','dois','doit','devons','devez','doivent'],imp:['devais','devais','devait','devions','deviez','devaient'],fut:['devrai','devras','devra','devrons','devrez','devront'],cond:['devrais','devrais','devrait','devrions','devriez','devraient'],subj:['doive','doives','doive','devions','deviez','doivent']},
  'mettre':{pres:['mets','mets','met','mettons','mettez','mettent'],imp:['mettais','mettais','mettait','mettions','mettiez','mettaient'],fut:['mettrai','mettras','mettra','mettrons','mettrez','mettront'],cond:['mettrais','mettrais','mettrait','mettrions','mettriez','mettraient'],subj:['mette','mettes','mette','mettions','mettiez','mettent']},
  'partir':{pres:['pars','pars','part','partons','partez','partent'],imp:['partais','partais','partait','partions','partiez','partaient'],fut:['partirai','partiras','partira','partirons','partirez','partiront'],cond:['partirais','partirais','partirait','partirions','partiriez','partiraient'],subj:['parte','partes','parte','partions','partiez','partent']},
  'sortir':{pres:['sors','sors','sort','sortons','sortez','sortent'],imp:['sortais','sortais','sortait','sortions','sortiez','sortaient'],fut:['sortirai','sortiras','sortira','sortirons','sortirez','sortiront'],cond:['sortirais','sortirais','sortirait','sortirions','sortiriez','sortiraient'],subj:['sorte','sortes','sorte','sortions','sortiez','sortent']},
  'tenir':{pres:['tiens','tiens','tient','tenons','tenez','tiennent'],imp:['tenais','tenais','tenait','tenions','teniez','tenaient'],fut:['tiendrai','tiendras','tiendra','tiendrons','tiendrez','tiendront'],cond:['tiendrais','tiendrais','tiendrait','tiendrions','tiendriez','tiendraient'],subj:['tienne','tiennes','tienne','tenions','teniez','tiennent']},
  'recevoir':{pres:['reçois','reçois','reçoit','recevons','recevez','reçoivent'],imp:['recevais','recevais','recevait','recevions','receviez','recevaient'],fut:['recevrai','recevras','recevra','recevrons','recevrez','recevront'],cond:['recevrais','recevrais','recevrait','recevrions','recevriez','recevraient'],subj:['reçoive','reçoives','reçoive','recevions','receviez','reçoivent']},
  'boire':{pres:['bois','bois','boit','buvons','buvez','boivent'],imp:['buvais','buvais','buvait','buvions','buviez','buvaient'],fut:['boirai','boiras','boira','boirons','boirez','boiront'],cond:['boirais','boirais','boirait','boirions','boiriez','boiraient'],subj:['boive','boives','boive','buvions','buviez','boivent']},
  'croire':{pres:['crois','crois','croit','croyons','croyez','croient'],imp:['croyais','croyais','croyait','croyions','croyiez','croyaient'],fut:['croirai','croiras','croira','croirons','croirez','croiront'],cond:['croirais','croirais','croirait','croirions','croiriez','croiraient'],subj:['croie','croies','croie','croyions','croyiez','croient']},
  'écrire':{pres:['écris','écris','écrit','écrivons','écrivez','écrivent'],imp:['écrivais','écrivais','écrivait','écrivions','écriviez','écrivaient'],fut:['écrirai','écriras','écrira','écrirons','écrirez','écriront'],cond:['écrirais','écrirais','écrirait','écririons','écririez','écriraient'],subj:['écrive','écrives','écrive','écrivions','écriviez','écrivent']},
  'lire':{pres:['lis','lis','lit','lisons','lisez','lisent'],imp:['lisais','lisais','lisait','lisions','lisiez','lisaient'],fut:['lirai','liras','lira','lirons','lirez','liront'],cond:['lirais','lirais','lirait','lirions','liriez','liraient'],subj:['lise','lises','lise','lisions','lisiez','lisent']},
  'connaître':{pres:['connais','connais','connaît','connaissons','connaissez','connaissent'],imp:['connaissais','connaissais','connaissait','connaissions','connaissiez','connaissaient'],fut:['connaîtrai','connaîtras','connaîtra','connaîtrons','connaîtrez','connaîtront'],cond:['connaîtrais','connaîtrais','connaîtrait','connaîtrions','connaîtriez','connaîtraient'],subj:['connaisse','connaisses','connaisse','connaissions','connaissiez','connaissent']},
  'suivre':{pres:['suis','suis','suit','suivons','suivez','suivent'],imp:['suivais','suivais','suivait','suivions','suiviez','suivaient'],fut:['suivrai','suivras','suivra','suivrons','suivrez','suivront'],cond:['suivrais','suivrais','suivrait','suivrions','suivriez','suivraient'],subj:['suive','suives','suive','suivions','suiviez','suivent']},
  'vivre':{pres:['vis','vis','vit','vivons','vivez','vivent'],imp:['vivais','vivais','vivait','vivions','viviez','vivaient'],fut:['vivrai','vivras','vivra','vivrons','vivrez','vivront'],cond:['vivrais','vivrais','vivrait','vivrions','vivriez','vivraient'],subj:['vive','vives','vive','vivions','viviez','vivent']},
  'courir':{pres:['cours','cours','court','courons','courez','courent'],imp:['courais','courais','courait','courions','couriez','couraient'],fut:['courrai','courras','courra','courrons','courrez','courront'],cond:['courrais','courrais','courrait','courrions','courriez','courraient'],subj:['coure','coures','coure','courions','couriez','courent']},
  'ouvrir':{pres:['ouvre','ouvres','ouvre','ouvrons','ouvrez','ouvrent'],imp:['ouvrais','ouvrais','ouvrait','ouvrions','ouvriez','ouvraient'],fut:['ouvrirai','ouvriras','ouvrira','ouvrirons','ouvrirez','ouvriront'],cond:['ouvrirais','ouvrirais','ouvrirait','ouvririons','ouvririez','ouvriraient'],subj:['ouvre','ouvres','ouvre','ouvrions','ouvriez','ouvrent']},
  'mourir':{pres:['meurs','meurs','meurt','mourons','mourez','meurent'],imp:['mourais','mourais','mourait','mourions','mouriez','mouraient'],fut:['mourrai','mourras','mourra','mourrons','mourrez','mourront'],cond:['mourrais','mourrais','mourrait','mourrions','mourriez','mourraient'],subj:['meure','meures','meure','mourions','mouriez','meurent']},
  'valoir':{pres:['vaux','vaux','vaut','valons','valez','valent'],imp:['valais','valais','valait','valions','valiez','valaient'],fut:['vaudrai','vaudras','vaudra','vaudrons','vaudrez','vaudront'],cond:['vaudrais','vaudrais','vaudrait','vaudrions','vaudriez','vaudraient'],subj:['vaille','vailles','vaille','valions','valiez','vaillent']},
  'craindre':{pres:['crains','crains','craint','craignons','craignez','craignent'],imp:['craignais','craignais','craignait','craignions','craigniez','craignaient'],fut:['craindrai','craindras','craindra','craindrons','craindrez','craindront'],cond:['craindrais','craindrais','craindrait','craindrions','craindriez','craindraient'],subj:['craigne','craignes','craigne','craignions','craigniez','craignent']},
  'perdre':{pres:['perds','perds','perd','perdons','perdez','perdent'],imp:['perdais','perdais','perdait','perdions','perdiez','perdaient'],fut:['perdrai','perdras','perdra','perdrons','perdrez','perdront'],cond:['perdrais','perdrais','perdrait','perdrions','perdriez','perdraient'],subj:['perde','perdes','perde','perdions','perdiez','perdent']},
  'vendre':{pres:['vends','vends','vend','vendons','vendez','vendent'],imp:['vendais','vendais','vendait','vendions','vendiez','vendaient'],fut:['vendrai','vendras','vendra','vendrons','vendrez','vendront'],cond:['vendrais','vendrais','vendrait','vendrions','vendriez','vendraient'],subj:['vende','vendes','vende','vendions','vendiez','vendent']},
  'attendre':{pres:['attends','attends','attend','attendons','attendez','attendent'],imp:['attendais','attendais','attendait','attendions','attendiez','attendaient'],fut:['attendrai','attendras','attendra','attendrons','attendrez','attendront'],cond:['attendrais','attendrais','attendrait','attendrions','attendriez','attendraient'],subj:['attende','attendes','attende','attendions','attendiez','attendent']},
  'répondre':{pres:['réponds','réponds','répond','répondons','répondez','répondent'],imp:['répondais','répondais','répondait','répondions','répondiez','répondaient'],fut:['répondrai','répondras','répondra','répondrons','répondrez','répondront'],cond:['répondrais','répondrais','répondrait','répondrions','répondriez','répondraient'],subj:['réponde','répondes','réponde','répondions','répondiez','répondent']},
  'appeler':{pres:['appelle','appelles','appelle','appelons','appelez','appellent'],imp:['appelais','appelais','appelait','appelions','appeliez','appelaient'],fut:['appellerai','appelleras','appellera','appellerons','appellerez','appelleront'],cond:['appellerais','appellerais','appellerait','appellerions','appelleriez','appelleraient'],subj:['appelle','appelles','appelle','appelions','appeliez','appellent']},
  'lever':{pres:['lève','lèves','lève','levons','levez','lèvent'],imp:['levais','levais','levait','levions','leviez','levaient'],fut:['lèverai','lèveras','lèvera','lèverons','lèverez','lèveront'],cond:['lèverais','lèverais','lèverait','lèverions','lèveriez','lèveraient'],subj:['lève','lèves','lève','levions','leviez','lèvent']},
  'battre':{pres:['bats','bats','bat','battons','battez','battent'],imp:['battais','battais','battait','battions','battiez','battaient'],fut:['battrai','battras','battra','battrons','battrez','battront'],cond:['battrais','battrais','battrait','battrions','battriez','battraient'],subj:['batte','battes','batte','battions','battiez','battent']},
  'mentir':{pres:['mens','mens','ment','mentons','mentez','mentent'],imp:['mentais','mentais','mentait','mentions','mentiez','mentaient'],fut:['mentirai','mentiras','mentira','mentirons','mentirez','mentiront'],cond:['mentirais','mentirais','mentirait','mentirions','mentiriez','mentiraient'],subj:['mente','mentes','mente','mentions','mentiez','mentent']},
  'peindre':{pres:['peins','peins','peint','peignons','peignez','peignent'],imp:['peignais','peignais','peignait','peignions','peigniez','peignaient'],fut:['peindrai','peindras','peindra','peindrons','peindrez','peindront'],cond:['peindrais','peindrais','peindrait','peindrions','peindriez','peindraient'],subj:['peigne','peignes','peigne','peignions','peigniez','peignent']},
  'produire':{pres:['produis','produis','produit','produisons','produisez','produisent'],imp:['produisais','produisais','produisait','produisions','produisiez','produisaient'],fut:['produirai','produiras','produira','produirons','produirez','produiront'],cond:['produirais','produirais','produirait','produirions','produiriez','produiraient'],subj:['produise','produises','produise','produisions','produisiez','produisent']},
  'résoudre':{pres:['résous','résous','résout','résolvons','résolvez','résolvent'],imp:['résolvais','résolvais','résolvait','résolvions','résolviez','résolvaient'],fut:['résoudrai','résoudras','résoudra','résoudrons','résoudrez','résoudront'],cond:['résoudrais','résoudrais','résoudrait','résoudrions','résoudriez','résoudraient'],subj:['résolve','résolves','résolve','résolvions','résolviez','résolvent']},
  'plaire':{pres:['plais','plais','plaît','plaisons','plaisez','plaisent'],imp:['plaisais','plaisais','plaisait','plaisions','plaisiez','plaisaient'],fut:['plairai','plairas','plaira','plairons','plairez','plairont'],cond:['plairais','plairais','plairait','plairions','plairiez','plairaient'],subj:['plaise','plaises','plaise','plaisions','plaisiez','plaisent']},
};

// ── Niveaux ──
const LEVELS=['CP','CE1','CE2','CM1','CM2','6e','5e','4e','3e','2de','1re','Tle'];
function lvlIdx(l){const i=LEVELS.indexOf(l);return i>=0?i:0;}
const XP_LEVELS=[
  {min:0,lbl:'Novice',ic:'🌱'},{min:80,lbl:'Apprenti',ic:'📖'},
  {min:200,lbl:'Élève',ic:'✏️'},{min:450,lbl:'Confirmé',ic:'🎒'},
  {min:850,lbl:'Expert',ic:'🎓'},{min:1500,lbl:'Érudit',ic:'⭐'},
  {min:3000,lbl:'Maître',ic:'🏆'}
];
function getXPLevel(xp){let l=XP_LEVELS[0];for(const lv of XP_LEVELS)if(xp>=lv.min)l=lv;return l;}

// ── Types d'exercices ──
const OPS=[
  {id:'conj_pres',lbl:'Présent',sub:'Indicatif présent',ic:'📝',min:'CP'},
  {id:'conj_imp',lbl:'Imparfait',sub:'Indicatif imparfait',ic:'📖',min:'CE2'},
  {id:'conj_fut',lbl:'Futur simple',sub:"Futur de l'indicatif",ic:'🚀',min:'CM1'},
  {id:'conj_pc',lbl:'Passé composé',sub:'Auxiliaire + participe',ic:'⏪',min:'CM1'},
  {id:'conj_pqp',lbl:'Plus-que-parfait',sub:'Temps du récit',ic:'⏮',min:'5e'},
  {id:'conj_cond',lbl:'Conditionnel',sub:'Conditionnel présent',ic:'🎭',min:'4e'},
  {id:'conj_subj',lbl:'Subjonctif',sub:'Subjonctif présent',ic:'🔮',min:'3e'},
  {id:'homo',lbl:'Homophones',sub:'a/à · on/ont · est/et',ic:'🔊',min:'CE2'},
  {id:'adj_accord',lbl:'Accord adj.',sub:'Genre & nombre',ic:'🔤',min:'CE2'},
  {id:'gn_accord',lbl:'Groupe nominal',sub:'Accord dans le GN',ic:'📐',min:'CM1'},
  {id:'nature',lbl:'Nature des mots',sub:'Nom · verbe · adj…',ic:'🏷',min:'CE1'},
  {id:'ortho',lbl:'Orthographe',sub:'Bien écrire les mots',ic:'✏️',min:'CE1'},
  {id:'synonyme',lbl:'Synonymes',sub:'Trouver le mot proche',ic:'🔗',min:'CE1'},
  {id:'antonyme',lbl:'Antonymes',sub:'Trouver le contraire',ic:'↔️',min:'CE1'},
  {id:'dictee',lbl:'Dictée',sub:'Écoute et écris la phrase',ic:'🎙',min:'CE1'},
  {id:'phrase_corr',lbl:'Corriger la phrase',sub:"Trouve et corrige l'erreur",ic:'🔍',min:'CE2'},
  {id:'genre',lbl:'Genre des noms',sub:'Masculin ou féminin ?',ic:'⚖️',min:'CP'},
];

// ── Homophones ── [phrase_avec_trou, correct, [faux], minLvl]
const HOMO=[
  ['Le chat ___ faim.','a',['à'],'CE2'],
  ['Elle va ___ la piscine.','à',['a'],'CE2'],
  ['Il pense ___ ses amis.','à',['a'],'CE2'],
  ['Le chien ___ mangé son repas.','a',['à'],'CE2'],
  ['___ joue dans le jardin.','On',['Ont'],'CE2'],
  ['Les enfants ___ faim.','ont',['on'],'CE2'],
  ['___ entend de la musique.','On',['Ont'],'CE2'],
  ['Mes parents ___ voyagé.','ont',['on'],'CE2'],
  ['Le ciel ___ bleu.','est',['et'],'CE2'],
  ['Il lit ___ écrit en même temps.','et',['est'],'CE2'],
  ['La fleur ___ rouge.','est',['et'],'CE2'],
  ['Elle chante ___ danse.','et',['est'],'CE2'],
  ['___ chien aboie fort.','Son',['Sont'],'CE2'],
  ['Les oiseaux ___ dans le ciel.','sont',['son'],'CE2'],
  ['Il range ___ cartable.','son',['sont'],'CE2'],
  ['Elles ___ arrivées en retard.','sont',['son'],'CE2'],
  ['Tu veux du lait ___ du jus ?','ou',['où'],'CE2'],
  ['___ habites-tu ?','Où',['Ou'],'CE2'],
  ['Je ne sais pas ___ il est.','où',['ou'],'CE2'],
  ['___ il était fatigué, il continua.','Mais',['Mes'],'CM1'],
  ['J\'ai oublié ___ affaires.','mes',['mais'],'CM1'],
  ['___ fleurs sont magnifiques.','Ces',['Ses'],'CM1'],
  ['Il promène ___ chiens.','ses',['ces'],'CM1'],
  ["___ mon livre préféré.",'C\'est',["S'est"],'CM1'],
  ["Elle ___ blessée en tombant.",'s\'est',["c'est"],'CM1'],
  ['___ le monde est arrivé.','Tout',['Tous'],'CM1'],
  ['___ les élèves ont réussi.','Tous',['Tout'],'CM1'],
  ['___ livre est à moi.','Ce',['Se'],'CM2'],
  ['Il ___ lave les mains.','se',['ce'],'CM2'],
  ['___ matin, il pleut.','Ce',['Se'],'CM2'],
  ['Pose-le ___.','là',["la","l'a"],'CM2'],
  ['Je prends ___ valise.','la',["là","l'a"],'CM2'],
  ["Il ___ vu hier.",'l\'a',['la','là'],'CM2'],
  ['___ sœur est venue.','Ma',["M'a"],'CM2'],
  ["Elle ___ appelé ce matin.",'m\'a',['ma'],'CM2'],
  ['Je ___ ai parlé hier.','leur',['leurs'],'CM2'],
  ['___ maison est grande.','Leur',['Leurs'],'CM2'],
  ['Ils ont pris ___ affaires.','leurs',['leur'],'CM2'],
  ['Il travaille ___ que son frère.','davantage',["d'avantage"],'6e'],
  ['___ fatigué, il continua.','Quoique',['Quoi que'],'6e'],
  ["Je ___ suis jamais allé.",'n\'y',['ni'],'5e'],
  ["Il ne vient ___ aujourd'hui.",'ni',["n'y"],'5e'],
  ['Il agit ___ qu\'il pense.','plutôt',['plus tôt'],'4e'],
  ['Il est arrivé ___ que prévu.','plus tôt',['plutôt'],'4e'],
  ['Il ___ levé très tôt ce matin.','s\'est',["c'est"],'CM1'],
  ['___ une bonne idée !','C\'est',["S'est"],'CM1'],
  ['Nous ___ promenés dans le parc.','nous sommes',['on a'],'5e'],
  ['Il ne ___ pas de ça.','s\'agit',["c'agit"],'5e'],
];

// ── Adjectifs ── [ms, fs, mp, fp, minLvl]
const ADJ=[
  ['grand','grande','grands','grandes','CE2'],
  ['petit','petite','petits','petites','CE2'],
  ['fort','forte','forts','fortes','CE2'],
  ['long','longue','longs','longues','CE2'],
  ['chaud','chaude','chauds','chaudes','CE2'],
  ['froid','froide','froids','froides','CE2'],
  ['blanc','blanche','blancs','blanches','CE2'],
  ['noir','noire','noirs','noires','CE2'],
  ['rouge','rouge','rouges','rouges','CE2'],
  ['vert','verte','verts','vertes','CE2'],
  ['bleu','bleue','bleus','bleues','CE2'],
  ['beau','belle','beaux','belles','CE2'],
  ['nouveau','nouvelle','nouveaux','nouvelles','CE2'],
  ['vieux','vieille','vieux','vieilles','CE2'],
  ['heureux','heureuse','heureux','heureuses','CM1'],
  ['gros','grosse','gros','grosses','CM1'],
  ['doux','douce','doux','douces','CM1'],
  ['faux','fausse','faux','fausses','CM1'],
  ['épais','épaisse','épais','épaisses','CM1'],
  ['bas','basse','bas','basses','CM1'],
  ['léger','légère','légers','légères','CM1'],
  ['dernier','dernière','derniers','dernières','CM1'],
  ['premier','première','premiers','premières','CM1'],
  ['entier','entière','entiers','entières','CM1'],
  ['régulier','régulière','réguliers','régulières','CM1'],
  ['gentil','gentille','gentils','gentilles','CM2'],
  ['pareil','pareille','pareils','pareilles','CM2'],
  ['cruel','cruelle','cruels','cruelles','CM2'],
  ['naturel','naturelle','naturels','naturelles','CM2'],
  ['actif','active','actifs','actives','CM2'],
  ['vif','vive','vifs','vives','CM2'],
  ['neuf','neuve','neufs','neuves','CM2'],
  ['bref','brève','brefs','brèves','CM2'],
  ['sot','sotte','sots','sottes','CM2'],
  ['muet','muette','muets','muettes','CM2'],
  ['jaloux','jalouse','jaloux','jalouses','6e'],
  ['roux','rousse','roux','rousses','6e'],
  ['amoureux','amoureuse','amoureux','amoureuses','6e'],
  ['cher','chère','chers','chères','6e'],
  ['fier','fière','fiers','fières','6e'],
  ['sec','sèche','secs','sèches','6e'],
  ['public','publique','publics','publiques','6e'],
  ['grec','grecque','grecs','grecques','6e'],
  ['demi','demie','demi','demies','5e'],
  ['tout','toute','tous','toutes','5e'],
  ['nul','nulle','nuls','nulles','5e'],
  ['tel','telle','tels','telles','5e'],
  ['mortel','mortelle','mortels','mortelles','5e'],
  ['pareil','pareille','pareils','pareilles','5e'],
  ['vermeil','vermeille','vermeils','vermeilles','4e'],
];

// ── Noms (accord) ── [ms, fs, mp, fp, minLvl]
const NOUNS=[
  ['homme','femme','hommes','femmes','CE1'],
  ['garçon','fille','garçons','filles','CE1'],
  ['chat','chatte','chats','chattes','CM1'],
  ['chanteur','chanteuse','chanteurs','chanteuses','CM1'],
  ['acteur','actrice','acteurs','actrices','CM2'],
  ['directeur','directrice','directeurs','directrices','CM2'],
  ['lion','lionne','lions','lionnes','CM2'],
  ['roi','reine','rois','reines','6e'],
  ['boulanger','boulangère','boulangers','boulangères','CM1'],
  ['écolier','écolière','écoliers','écolières','CE2'],
  ['élève','élève','élèves','élèves','CE2'],
  ['ami','amie','amis','amies','CE1'],
];

// ── Groupes nominaux ── [déterminant, nom, adj_ms, genre, nombre, minLvl]
const GN=[
  ['un','chat','noir','m','s','CE2'],
  ['une','fleur','rouge','f','s','CE2'],
  ['le','jardin','grand','m','s','CE2'],
  ['la','maison','blanc','f','s','CE2'],
  ['les','oiseaux','bleu','m','p','CE2'],
  ['les','filles','grand','f','p','CE2'],
  ['un','livre','vieux','m','s','CM1'],
  ['une','histoire','beau','f','s','CM1'],
  ['des','garçons','gentil','m','p','CM1'],
  ['des','fenêtres','ouvert','f','p','CM1'],
  ['un','animal','léger','m','s','CM2'],
  ['une','leçon','difficile','f','s','CM2'],
  ['des','solutions','nouveau','f','p','CM2'],
  ['un','élève','sérieux','m','s','6e'],
  ['une','chanson','doux','f','s','6e'],
  ['des','problèmes','complexe','m','p','6e'],
  ['un','regard','vif','m','s','6e'],
  ['des','routes','long','f','p','5e'],
  ['un','choix','difficile','m','s','5e'],
  ['une','réponse','bref','f','s','5e'],
];

// ── Nature des mots ── [phrase, mot_cible, correct, [faux], minLvl]
const NATURE=[
  ['Le __chat__ dort.','chat','nom',['verbe','adjectif','adverbe'],'CE1'],
  ['Il __court__ vite.','court','verbe',['nom','adjectif','adverbe'],'CE1'],
  ['La __grande__ maison.','grande','adjectif',['nom','verbe','adverbe'],'CE1'],
  ['Elle chante __bien__.','bien','adverbe',['nom','verbe','adjectif'],'CE1'],
  ['__Le__ chat dort.','Le','déterminant',['nom','verbe','préposition'],'CE2'],
  ['Il parle __à__ Marie.','à','préposition',['déterminant','verbe','adjectif'],'CE2'],
  ['__Elle__ joue.','Elle','pronom',['nom','verbe','adjectif'],'CE2'],
  ['Il court __très__ vite.','très','adverbe',['nom','verbe','adjectif'],'CM1'],
  ['__Mais__ il est tard.','Mais','conjonction',['déterminant','adjectif','adverbe'],'CM1'],
  ['__Hélas__!','Hélas','interjection',['nom','verbe','adverbe'],'CM1'],
  ['La maison __de__ mon ami.','de','préposition',['déterminant','conjonction','adverbe'],'CM1'],
  ['Je vais __chez__ le médecin.','chez','préposition',['déterminant','adverbe','conjonction'],'CM2'],
  ['__Nous__ travaillons.','Nous','pronom',['nom','verbe','adjectif'],'CM2'],
  ['Il est venu __car__ il avait faim.','car','conjonction',['préposition','adverbe','pronom'],'CM2'],
  ['__Bravo__ !','Bravo','interjection',['adjectif','adverbe','nom'],'CM2'],
  ['Elle est __souvent__ absente.','souvent','adverbe',['adjectif','nom','conjonction'],'6e'],
  ['La __beauté__ du paysage.','beauté','nom',['verbe','adjectif','adverbe'],'CM1'],
  ['__Pourquoi__ pleures-tu ?','Pourquoi','adverbe',['conjonction','préposition','déterminant'],'CM2'],
  ['Il habite __là-bas__.','là-bas','adverbe',['préposition','nom','adjectif'],'CM1'],
  ['__Leur__ maison est belle.','Leur','déterminant',['pronom','adjectif','adverbe'],'CM2'],
  ['Il chante __et__ danse.','et','conjonction',['préposition','adverbe','déterminant'],'CE2'],
  ['__Quoique__ fatigué, il travailla.','Quoique','conjonction',['préposition','adverbe','pronom'],'5e'],
  ['Elle parle __doucement__.','doucement','adverbe',['adjectif','nom','verbe'],'CM1'],
  ['Il a une __belle__ voiture.','belle','adjectif',['nom','adverbe','pronom'],'CE2'],
  ['__Mon__ chien est gentil.','Mon','déterminant',['pronom','adjectif','conjonction'],'CE1'],
];

// ── Orthographe ── [correct, faux1, faux2, faux3, faux4, minLvl]
const ORTHO=[
  ['maison','maisson','maisont','mazon','maizon','CP'],
  ['école','ecole','ekole','éscole','échôle','CP'],
  ['soleil','solei','soleille','solleil','souleil','CP'],
  ['oiseau','oizeau','oisaux','oisseau','oiseo','CP'],
  ['cahier','caier','cahié','kaier','cahiaire','CE1'],
  ['tableau','tableo','tablau','tablo','tablaux','CE1'],
  ['cerise','serise','cherise','cerice','cerlise','CE1'],
  ['crayon','creyons','craiyon','craion','creyont','CE1'],
  ['fenêtre','fenetre','fenètre','fennettre','fênetre','CE1'],
  ['grenouille','grenouile','grenuille','grenouylle','grenuiylle','CE2'],
  ['papillon','papilion','pappillon','papilyon','papiyon','CE2'],
  ['château','chateau','châtaud','chatôt','chataud','CE2'],
  ['champignon','chanpignon','champignion','champigon','champinnon','CE2'],
  ['écureuil','écureille','ecureuil','éscureuil','éskureuil','CE2'],
  ['médecin','médecain','médesin','médeçin','médcin','CM1'],
  ['printemps','preintemps','printant','printamps','praintemps','CM1'],
  ['automne','autone','automone','autonne','autonme','CM1'],
  ['famille','famile','famiye','failme','famiyle','CM1'],
  ['difficile','dificile','difficille','diffisile','difficil','CM1'],
  ['cœur','coeur','queur','choeur','quoeur','CM2'],
  ['œil','eil','oeuil','oeill','oueil','CM2'],
  ['nœud','noeud','noeux','noud','noued','CM2'],
  ['développer','developper','développper','developpez','développée','6e'],
  ['appartement','appartament','apartemant','appartment','appertement','6e'],
  ['exceptionnel','exseptionnel','exceptionel','exzeptionnel','exeptionnel','6e'],
  ['conscient','consient','consciant','conssiants','consiènt','5e'],
  ['rythme','ritme','rhytme','rythmme','rithme','5e'],
  ['gymnaste','gimnaste','gymnasste','gymnastiqu','gynmaste','CM2'],
  ['nénuphar','nenuphar','nénupar','nénufar','nénuphard','4e'],
  ['yacht','yatsh','yach','yatcht','iatsh','4e'],
  ['oignon','oingnon','ognion','oignion','oingnion','5e'],
  ['abîme','abime','abîmme','abymes','abimme','6e'],
  ['chrysanthème','crysanthème','chrysantème','chrisanthème','chrysanntème','CM2'],
  ['perpendiculaire','perpandiculaire','perpendicullaire','perpendiculère','perpediculaire','5e'],
  ['homogène','homojène','homogenne','omogène','homôgène','5e'],
  ['hypothèse','hipothèse','hypothese','hyppothèse','hypothèze','4e'],
  ['parallèle','paralèle','parallelle','paralelle','parralèle','4e'],
  ['vocabulaire','vocabolaire','vocabulère','vocaboulaire','vocabaulaire','CM1'],
  ['grammaire','gramaire','grammère','grammair','gramayre','CE2'],
  ['orthographe','ortographe','orthografe','hortographe','orthographfe','CE2'],
];

// ── Synonymes ──
// [mot, synonyme_correct, [faux_proches_mais_pas_exacts], minLvl]
const SYNO=[
  // CE1 — leurres = synonymes proches mais pas exacts
  ['content','heureux',['satisfait','ravi','enchanté'],'CE1'],
  ['triste','malheureux',['chagriné','morose','mélancolique'],'CE1'],
  ['rapide','vite',['prompt','pressé','brusque'],'CE1'],
  ['grand','immense',['vaste','gigantesque','énorme'],'CE1'],
  ['petit','minuscule',['menu','infime','microscopique'],'CE1'],
  ['beau','joli',['magnifique','splendide','superbe'],'CE1'],
  ['ami','camarade',['copain','compagnon','associé'],'CE1'],
  ['maison','demeure',['habitation','logement','domicile'],'CE1'],
  ['regarder','observer',['contempler','examiner','fixer'],'CE1'],
  ['marcher','avancer',['déambuler','cheminer','progresser'],'CE1'],
  // CE2
  ['chaud','brûlant',['tiède','ardent','torride'],'CE2'],
  ['froid','glacial',['frais','gelé','frigide'],'CE2'],
  ['fort','puissant',['robuste','vigoureux','solide'],'CE2'],
  ['faible','fragile',['chétif','délicat','frêle'],'CE2'],
  ['courageux','brave',['vaillant','audacieux','intrépide'],'CE2'],
  ['peureux','craintif',['timide','hésitant','timoré'],'CE2'],
  ['gentil','aimable',['doux','bienveillant','attentionné'],'CE2'],
  ['méchant','cruel',['malveillant','mauvais','hostile'],'CE2'],
  ['parler','discuter',['converser','bavarder','dialoguer'],'CE2'],
  ['commencer','débuter',['entamer','amorcer','initier'],'CE2'],
  ['finir','terminer',['achever','clore','conclure'],'CE2'],
  ['dormir','sommeiller',['assoupir','reposer','siester'],'CE2'],
  ['tomber','chuter',['dégringoler','trébucher','s\'effondrer'],'CE2'],
  ['cacher','dissimuler',['masquer','occulter','voiler'],'CE2'],
  ['chercher','quêter',['fouiller','explorer','prospecter'],'CE2'],
  // CM1
  ['fatigué','épuisé',['las','éreinté','exténué'],'CM1'],
  ['colère','fureur',['rage','courroux','irritation'],'CM1'],
  ['peur','crainte',['appréhension','angoisse','frayeur'],'CM1'],
  ['aide','secours',['assistance','soutien','appui'],'CM1'],
  ['bizarre','étrange',['curieux','singulier','insolite'],'CM1'],
  ['difficile','ardu',['complexe','épineux','laborieux'],'CM1'],
  ['facile','aisé',['simple','accessible','élémentaire'],'CM1'],
  ['vieux','ancien',['antique','suranné','désuet'],'CM1'],
  ['neuf','récent',['nouveau','moderne','contemporain'],'CM1'],
  ['trouver','découvrir',['dénicher','repérer','déceler'],'CM1'],
  ['rapide','prompt',['alerte','vif','preste'],'CM1'],
  ['lent','nonchalant',['languissant','traînant','apathique'],'CM1'],
  ['riche','aisé',['opulent','fortuné','prospère'],'CM1'],
  ['pauvre','indigent',['démuni','nécessiteux','misérable'],'CM1'],
  // CM2
  ['joyeux','gai',['enjoué','jovial','allègre'],'CM2'],
  ['calme','serein',['paisible','tranquille','apaisé'],'CM2'],
  ['intelligent','habile',['astucieux','perspicace','ingénieux'],'CM2'],
  ['penser','réfléchir',['méditer','songer','cogiter'],'CM2'],
  ['construire','bâtir',['édifier','ériger','élever'],'CM2'],
  ['détruire','démolir',['raser','abattre','anéantir'],'CM2'],
  ['montrer','exhiber',['exposer','révéler','présenter'],'CM2'],
  ['utiliser','employer',['exploiter','recourir','mobiliser'],'CM2'],
  ['obtenir','acquérir',['décrocher','arracher','soutirer'],'CM2'],
  ['répondre','répliquer',['rétorquer','objecter','contredire'],'CM2'],
  // 6e
  ['lumineux','éclatant',['brillant','resplendissant','rayonnant'],'6e'],
  ['sombre','obscur',['ténébreux','opaque','assombri'],'6e'],
  ['mystérieux','énigmatique',['sibyllin','impénétrable','hermétique'],'6e'],
  ['courageux','intrépide',['téméraire','audacieux','vaillant'],'6e'],
  ['sage','prudent',['sensé','avisé','raisonnable'],'6e'],
  ['généreux','prodigue',['libéral','charitable','altruiste'],'6e'],
  ['avare','pingre',['radin','mesquin','ladre'],'6e'],
  ['honnête','intègre',['probe','loyal','droit'],'6e'],
  ['espoir','espérance',['attente','foi','confiance'],'6e'],
  ['peine','chagrin',['douleur','affliction','tourment'],'6e'],
  // 5e+
  ['abondant','copieux',['plantureux','foisonnant','prolifique'],'5e'],
  ['rare','précieux',['singulier','insolite','exceptionnel'],'5e'],
  ['apparent','visible',['manifeste','patent','ostensible'],'5e'],
  ['caché','latent',['sous-jacent','occulte','recélé'],'5e'],
  ['vague','imprécis',['flou','approximatif','nébuleux'],'5e'],
  ['précis','exact',['rigoureux','minutieux','pointu'],'5e'],
  ['permettre','autoriser',['tolérer','accepter','admettre'],'5e'],
  ['interdire','prohiber',['défendre','bannir','exclure'],'5e'],
];

// ── Antonymes ──
// [mot, antonyme_correct, [faux_dans_le_même_champ_sémantique], minLvl]
const ANTO=[
  // CE1
  ['grand','petit',['court','bas','mince'],'CE1'],
  ['petit','grand',['haut','long','épais'],'CE1'],
  ['jour','nuit',['soir','crépuscule','aube'],'CE1'],
  ['nuit','jour',['matin','midi','après-midi'],'CE1'],
  ['chaud','froid',['tiède','frais','glacé'],'CE1'],
  ['froid','chaud',['tiède','doux','brûlant'],'CE1'],
  ['fort','faible',['fragile','doux','léger'],'CE1'],
  ['content','mécontent',['triste','déçu','chagriné'],'CE1'],
  ['propre','sale',['souillé','crasseux','immonde'],'CE1'],
  ['beau','laid',['moche','terne','disgracieux'],'CE1'],
  // CE2
  ['rapide','lent',['nonchalant','traînant','mou'],'CE2'],
  ['vrai','faux',['inexact','erroné','mensonger'],'CE2'],
  ['ami','ennemi',['adversaire','rival','opposant'],'CE2'],
  ['allumer','éteindre',['obscurcir','assombrir','noircir'],'CE2'],
  ['ouvrir','fermer',['clore','verrouiller','boucher'],'CE2'],
  ['monter','descendre',['tomber','dégringoler','plonger'],'CE2'],
  ['entrer','sortir',['quitter','partir','fuir'],'CE2'],
  ['chaud','froid',['tiède','frais','glacé'],'CE2'],
  ['plein','vide',['creux','vague','dégarni'],'CE2'],
  ['lourd','léger',['aérien','mince','fluide'],'CE2'],
  // CM1
  ['commencer','finir',['terminer','achever','conclure'],'CM1'],
  ['rire','pleurer',['sangloter','pleurnicher','geindre'],'CM1'],
  ['facile','difficile',['complexe','ardu','laborieux'],'CM1'],
  ['gentil','méchant',['cruel','malveillant','hostile'],'CM1'],
  ['courage','lâcheté',['couardise','poltronnerie','timidité'],'CM1'],
  ['riche','pauvre',['démuni','indigent','nécessiteux'],'CM1'],
  ['plein','vide',['creux','dégarni','lacunaire'],'CM1'],
  ['avancer','reculer',['retraiter','céder','fuir'],'CM1'],
  // CM2
  ['clair','sombre',['obscur','ténébreux','opaque'],'CM2'],
  ['doux','rude',['brutal','brusque','sévère'],'CM2'],
  ['intérieur','extérieur',['dehors','au-delà','alentour'],'CM2'],
  ['présent','absent',['lointain','éloigné','parti'],'CM2'],
  ['réussir','échouer',['rater','manquer','faillir'],'CM2'],
  ['construire','démolir',['détruire','abattre','raser'],'CM2'],
  ['acheter','vendre',['céder','revendre','troquer'],'CM2'],
  ['demander','répondre',['répliquer','rétorquer','objecter'],'CM2'],
  // 6e
  ['optimiste','pessimiste',['défaitiste','alarmiste','sceptique'],'6e'],
  ['courageux','lâche',['peureux','craintif','hésitant'],'6e'],
  ['généreux','avare',['égoïste','radin','mesquin'],'6e'],
  ['honnête','malhonnête',['fourbe','trompeur','hypocrite'],'6e'],
  ['paix','guerre',['conflit','combat','belligérance'],'6e'],
  ['ancien','moderne',['récent','nouveau','contemporain'],'6e'],
  ['clarté','obscurité',['ombre','opacité','noirceur'],'6e'],
  ['liberté','servitude',['esclavage','contrainte','joug'],'6e'],
  // 5e+
  ['abondant','rare',['précieux','singulier','limité'],'5e'],
  ['apparent','caché',['latent','occulte','dissimulé'],'5e'],
  ['actif','passif',['inactif','oisif','immobile'],'5e'],
  ['complexe','simple',['élémentaire','basique','rudimentaire'],'5e'],
  ['superficiel','profond',['intense','abyssal','pénétrant'],'5e'],
  ['permettre','interdire',['prohiber','défendre','bannir'],'5e'],
  ['attirer','repousser',['éloigner','rebuter','écarter'],'5e'],
];

// ── Dictée ── [phrase, minLvl]
const DICTEE_DATA=[
  // CP
  ['Le chat dort.','CP'],
  ['La balle est rouge.','CP'],
  ['Mon ami joue.','CP'],
  ['Le soleil brille.','CP'],
  ['Il fait beau.','CP'],
  // CE1
  ['Le chien court dans le jardin.','CE1'],
  ['Ma mère prépare le repas.','CE1'],
  ['Les enfants jouent au ballon.','CE1'],
  ['Le lapin mange des carottes.','CE1'],
  ['Elle lit un livre intéressant.','CE1'],
  ['Le petit chat boit du lait.','CE1'],
  ['Mon papa travaille tous les jours.','CE1'],
  ["Il fait beau aujourd'hui.",'CE1'],
  ['Je range mes affaires dans ma chambre.','CE1'],
  ['La maîtresse lit une belle histoire.','CE1'],
  // CE2
  ['Le petit chat blanc dort sur le canapé.','CE2'],
  ['Les grandes fleurs rouges poussent dans le jardin.','CE2'],
  ['Mon frère aime beaucoup le chocolat.','CE2'],
  ['Les enfants sont partis à l\'école.','CE2'],
  ['Notre maison est à côté de la forêt.','CE2'],
  ['Le chat gris saute sur la chaise.','CE2'],
  ['Elle range ses affaires dans son cartable.','CE2'],
  ['Les élèves écrivent une belle histoire.','CE2'],
  ['Nous avons joué au foot avec nos amis.','CE2'],
  ['Le soir, ma grand-mère raconte des histoires.','CE2'],
  // CM1
  ['Le vieux château se dresse au sommet de la colline.','CM1'],
  ['La maîtresse corrige les cahiers de ses élèves.','CM1'],
  ['Pendant les vacances, nous allons à la montagne.','CM1'],
  ['Les élèves ont travaillé toute la journée avec sérieux.','CM1'],
  ['Le jardinier plante des fleurs sous le soleil du matin.','CM1'],
  ['Mon grand-père raconte de belles histoires le soir.','CM1'],
  ['Le renard roux traverse rapidement la forêt silencieuse.','CM1'],
  ['Chaque matin, elle prépare son cartable avec soin.','CM1'],
  // CM2
  ['Les beaux oiseaux blancs s\'envolaient au-dessus du lac.','CM2'],
  ['La cuisinière préparait un délicieux gâteau au chocolat.','CM2'],
  ['Malgré le froid, les enfants jouaient dehors avec enthousiasme.','CM2'],
  ['La bibliothèque municipale possède des milliers de livres.','CM2'],
  ['Les explorateurs traversèrent la forêt pendant trois jours.','CM2'],
  ['Il avait soigneusement plié sa lettre avant de l\'envoyer.','CM2'],
  // 6e
  ['Il était une fois une vieille sorcière qui vivait seule.','6e'],
  ['Les explorateurs parcouraient les forêts à la recherche de trésors.','6e'],
  ['Bien qu\'il fît froid, les enfants jouaient dehors avec enthousiasme.','6e'],
  ['La rivière coulait doucement entre les rochers recouverts de mousse.','6e'],
  ['Depuis le sommet, on apercevait les lumières de la ville au loin.','6e'],
  ['Quoique fatigué, il poursuivit sa route sans se plaindre.','6e'],
  // 5e
  ["Lorsqu'elle arriva, tout le monde s'était déjà réuni autour de la table.",'5e'],
  ["Les scientifiques ont découvert une nouvelle espèce d'insecte en Amazonie.",'5e'],
  ["Le philosophe affirme que la connaissance est la source de la liberté.",'5e'],
  ["Il suffit parfois d'un seul mot pour changer le cours d'une conversation.",'5e'],
  // 4e+
  ["Malgré ses efforts considérables, il n'avait pas réussi à convaincre ses adversaires.",'4e'],
  ["La beauté de ce paysage m'a profondément ému lors de mon premier voyage.",'4e'],
  ["Les hypothèses scientifiques doivent être vérifiées par l'expérience.",'4e'],
  ["Ce roman, dont l'intrigue se déroule au XVIIe siècle, est d'une grande complexité.",'3e'],
];

// ── Phrases à corriger ──
// [phrase_erreur, mot_faux, correction, [distracteurs_morphologiques], explication, minLvl]
const PHRASE_CORR=[
  // ── Accord sujet-verbe ──
  ['Les enfants joue dans le jardin.','joue','jouent',
    ['joue','joues','jouons'],
    'Sujet pluriel "les enfants" → terminaison -ent.','CE2'],
  ['Le chat et le chien mange ensemble.','mange','mangent',
    ['mange','manges','mangeons'],
    'Deux sujets coordonnés = pluriel → -ent.','CM1'],
  ['Vous doit travailler plus sérieusement.','doit','devez',
    ['doit','doivent','dois'],
    '"Vous" → "devoir" prend -ez.','CM1'],
  ['Ils court très vite sur la piste.','court','courent',
    ['court','courts','courez'],
    '"Ils" → terminaison -ent.','CE2'],
  ['Elle chante et ses amies aussi chante.','chante','chantent',
    ['chante','chantons','chantez'],
    '"Ses amies" = sujet pluriel → -ent.','CE2'],
  ['Mon père et ma mère travaille beaucoup.','travaille','travaillent',
    ['travaille','travailles','travaillons'],
    'Deux sujets = pluriel → -ent.','CM1'],
  ['Ni lui ni elle ne vient aujourd\'hui.','vient','viennent',
    ['vient','viens','venez'],
    '"Ni... ni..." avec deux sujets → pluriel.','5e'],
  // ── Accord adjectif ──
  ['Elle a acheté des roses rouge.','rouge','rouges',
    ['rouge','rougeâtre','rougis'],
    '"Roses" est féminin pluriel → -es.','CE2'],
  ['Les garçons semblaient très content.','content','contents',
    ['content','contente','contentes'],
    'Adjectif attribut masculin pluriel → -s.','CM1'],
  ['Le chat et la chienne sont belle.','belle','beaux',
    ['belle','belles','bel'],
    'Deux sujets dont un masculin → masculin pluriel.','CM2'],
  ['Les filles paraissaient fatigué.','fatigué','fatiguées',
    ['fatiguée','fatigués','fatigué'],
    'Adjectif attribut féminin pluriel → -ées.','CM1'],
  ['Ce sont des histoires passionnant.','passionnant','passionnantes',
    ['passionnant','passionnants','passionnante'],
    '"Histoires" féminin pluriel → -antes.','CM2'],
  ['Il a les yeux grand ouvert.','grand','grands',
    ['grande','grandes','grand'],
    '"Yeux" est masculin pluriel → -s.','CM2'],
  // ── Participe passé avec être ──
  ['Les élèves sont arrivé en retard.','arrivé','arrivés',
    ['arrivé','arrivée','arrivées'],
    'Avec "être", accord avec le sujet masculin pluriel → -és.','CM2'],
  ['Nous sommes aller au cinéma hier.','aller','allés',
    ['aller','allé','allées'],
    'Avec "être", participe accordé avec le sujet.','5e'],
  ['Elle est tombé dans l\'escalier.','tombé','tombée',
    ['tombé','tombés','tomber'],
    'Sujet féminin singulier → participe en -ée.','CM2'],
  ['Mes sœurs sont parti en voyage.','parti','parties',
    ['partis','partie','partir'],
    'Sujet féminin pluriel → participe en -ies.','CM2'],
  ['Il est rentré, elle aussi est rentré.','rentré','rentrée',
    ['rentrés','rentrer','rentrai'],
    'Sujet féminin singulier → accord en -ée.','CM2'],
  // ── Participe passé avec avoir ──
  ['Les lettres que j\'ai écrit.','écrit','écrites',
    ['écrit','écrits','écrire'],
    'COD "lettres" féminin pluriel avant le verbe → -es.','5e'],
  ['La chanson qu\'il a composé est belle.','composé','composée',
    ['composé','composés','composer'],
    '"Chanson" COD féminin singulier avant → -ée.','5e'],
  ['Les films que nous avons regardé.','regardé','regardés',
    ['regardé','regardée','regarder'],
    'COD "films" masculin pluriel avant → -és.','5e'],
  ['Elle les a tous invité.','invité','invités',
    ['invité','invitée','inviter'],
    '"Les" = COD masculin pluriel avant le verbe → -és.','5e'],
  ['La robe qu\'elle a cousue est belle.','cousue','cousue',
    ['cousu','cousus','coudre'],
    '"Robe" COD féminin singulier avant → -ue. Déjà correct.','4e'],
  // ── Homophones ──
  ['On a beaucoup de choses a faire.','a','à',
    ['a','as','ont'],
    '"À" préposition ≠ "a" verbe avoir.','CE2'],
  ['Il a mit son manteau avant de sortir.','mit','mis',
    ['mit','mît','mettre'],
    'Le participe passé de "mettre" s\'écrit "mis".','CM2'],
  ["Elle c'est trompée de chemin.",'c\'est','s\'est',
    ["c'est","c'était","s'était"],
    '"S\'est" = passé composé pronominal.','CM2'],
  ['Le chat dort sur sont coussin.','sont','son',
    ['sont','ont','mon'],
    '"Son" est un déterminant possessif.','CE2'],
  ['Il ce couche tôt tous les soirs.','ce','se',
    ['ce','ses','ces'],
    '"Se" est un pronom réfléchi (se coucher).','CM1'],
  // ── Orthographe ──
  ['Il est toujours fatigé après le sport.','fatigé','fatigué',
    ['fatigé','fatiguais','fatiguer'],
    '"Fatigué" s\'écrit avec u avant le é.','CE2'],
  ['La maitresse a expliqué la leçon.','maitresse','maîtresse',
    ['maitresse','maîtresses','maîtrèsse'],
    '"Maîtresse" prend un accent circonflexe sur le î.','CM2'],
  ['Il pleut, prenez vos paraluies.','paraluies','parapluies',
    ['paraluies','parapluie','para-pluies'],
    '"Parapluie" s\'écrit p-a-r-a-p-l-u-i-e.','CM1'],
  ['Les cerisiers sont en fleure au printemps.','fleure','fleur',
    ['fleure','fleures','fleurt'],
    '"Fleur" ne prend pas de -e final.','CE2'],
];

// ── Genre des noms ── [mot, genre_correct, [faux], minLvl]
const GENRE_DATA=[
  // CP/CE1
  ['soleil','masculin',['féminin'],'CP'],
  ['lune','féminin',['masculin'],'CP'],
  ['chien','masculin',['féminin'],'CP'],
  ['fleur','féminin',['masculin'],'CP'],
  ['arbre','masculin',['féminin'],'CE1'],
  ['table','féminin',['masculin'],'CE1'],
  ['livre','masculin',['féminin'],'CE1'],
  ['maison','féminin',['masculin'],'CE1'],
  ['jardin','masculin',['féminin'],'CE1'],
  ['école','féminin',['masculin'],'CE1'],
  ['ballon','masculin',['féminin'],'CE1'],
  ['forêt','féminin',['masculin'],'CE1'],
  // CE2/CM1
  ['tomate','féminin',['masculin'],'CE2'],
  ['nuage','masculin',['féminin'],'CE2'],
  ['plage','féminin',['masculin'],'CE2'],
  ['silence','masculin',['féminin'],'CE2'],
  ['image','féminin',['masculin'],'CM1'],
  ['problème','masculin',['féminin'],'CM1'],
  ['musique','féminin',['masculin'],'CM1'],
  ['sourire','masculin',['féminin'],'CM1'],
  ['courage','masculin',['féminin'],'CM1'],
  ['amour','masculin',['féminin'],'CM1'],
  ['légume','masculin',['féminin'],'CM1'],
  ['incendie','masculin',['féminin'],'CM1'],
  ['comète','féminin',['masculin'],'CM1'],
  ['pétale','masculin',['féminin'],'CM2'],
  ['oasis','féminin',['masculin'],'CM2'],
  ['tentacule','masculin',['féminin'],'CM2'],
  ['espace','masculin',['féminin'],'CM2'],
  ['manche','féminin',['masculin'],'CM2'],
  ['tour','féminin',['masculin'],'CM2'],
  ['poêle','masculin',['féminin'],'CM2'],
  ['voile','masculin',['féminin'],'CM2'],
  // 6e — pièges classiques
  ['ivoire','masculin',['féminin'],'6e'],
  ['amalgame','masculin',['féminin'],'6e'],
  ['effluve','masculin',['féminin'],'6e'],
  ['astérisque','masculin',['féminin'],'6e'],
  ['épithète','féminin',['masculin'],'6e'],
  ['enzyme','féminin',['masculin'],'6e'],
  ['anagramme','féminin',['masculin'],'6e'],
  ['énigme','féminin',['masculin'],'6e'],
  // 5e+
  ['alvéole','féminin',['masculin'],'5e'],
  ['azalée','féminin',['masculin'],'5e'],
  ['obélisque','masculin',['féminin'],'5e'],
  ['hémisphère','masculin',['féminin'],'5e'],
  ['armistice','masculin',['féminin'],'4e'],
  ['apogée','masculin',['féminin'],'4e'],
  ['équinoxe','masculin',['féminin'],'3e'],
  ['sortilège','masculin',['féminin'],'3e'],
  ['chrysalide','féminin',['masculin'],'3e'],
  ['phalange','féminin',['masculin'],'4e'],
];

// ── Constantes de jeu ──
const TENSE_LBL={pres:'présent',imp:'imparfait',fut:'futur simple',pc:'passé composé',pqp:'plus-que-parfait',cond:'conditionnel présent',subj:'subjonctif présent'};
const SUBJECTS=['je','tu','il/elle','nous','vous','ils/elles'];
const SUBJ_S=['je','tu','il','nous','vous','ils'];
const AVATS=['🧒','👦','👧','🧑','👨','👩','🧔','👴','👵','🎓','🦊','🐼','🐸','🦁','🐧','🤖','👾','🧸','🌟','🏆'];

// ── Badges ──
const BADGES=[
  {id:'first',ic:'🎯',nm:'Premier pas',cond:p=>p.totalQ>=1},
  {id:'x10',ic:'🔟',nm:'10 questions',cond:p=>p.totalQ>=10},
  {id:'x100',ic:'💯',nm:'Centurion',cond:p=>p.totalQ>=100},
  {id:'x500',ic:'🏅',nm:'Marathonien',cond:p=>p.totalQ>=500},
  {id:'perfect',ic:'⭐',nm:'Sans faute',cond:p=>p.perfectRounds>=1},
  {id:'p5',ic:'🌟',nm:'5 sessions parfaites',cond:p=>p.perfectRounds>=5},
  {id:'combo5',ic:'🔥',nm:'Combo x5',cond:p=>p.maxCombo>=5},
  {id:'combo10',ic:'💥',nm:'Combo x10',cond:p=>p.maxCombo>=10},
  {id:'xp500',ic:'⚡',nm:'500 XP',cond:p=>p.xp>=500},
  {id:'xp2000',ic:'💎',nm:'2000 XP',cond:p=>p.xp>=2000},
  {id:'conj30',ic:'📝',nm:'30 conjugaisons',cond:p=>(p.conjOk||0)>=30},
  {id:'homo20',ic:'🔊',nm:'20 homophones',cond:p=>(p.homoOk||0)>=20},
  {id:'ortho20',ic:'✏️',nm:'20 orthos',cond:p=>(p.orthoOk||0)>=20},
  {id:'syno20',ic:'🔗',nm:'20 synonymes',cond:p=>(p.synoOk||0)>=20},
  {id:'revision',ic:'🔁',nm:'Réviseur',cond:p=>(p.revisionDone||0)>=1},
  {id:'all_types',ic:'🎓',nm:'Touche-à-tout',cond:p=>Object.keys(p.typeStats||{}).length>=8},
];
